// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1/health.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1;

@com.google.protobuf.Generated
public final class Health {
  private Health() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      Health.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_inventory_v1_GetLivezRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kessel_inventory_v1_GetLivezRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_inventory_v1_GetLivezResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kessel_inventory_v1_GetLivezResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_inventory_v1_GetReadyzRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kessel_inventory_v1_GetReadyzRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_inventory_v1_GetReadyzResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kessel_inventory_v1_GetReadyzResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n kessel/inventory/v1/health.proto\022\023kess" +
      "el.inventory.v1\032\034google/api/annotations." +
      "proto\"\021\n\017GetLivezRequest\">\n\020GetLivezResp" +
      "onse\022\026\n\006status\030\001 \001(\tR\006status\022\022\n\004code\030\002 \001" +
      "(\rR\004code\"\022\n\020GetReadyzRequest\"?\n\021GetReady" +
      "zResponse\022\026\n\006status\030\001 \001(\tR\006status\022\022\n\004cod" +
      "e\030\002 \001(\rR\004code2\226\002\n\034KesselInventoryHealthS" +
      "ervice\022x\n\010GetLivez\022$.kessel.inventory.v1" +
      ".GetLivezRequest\032%.kessel.inventory.v1.G" +
      "etLivezResponse\"\037\202\323\344\223\002\031\022\027/api/inventory/" +
      "v1/livez\022|\n\tGetReadyz\022%.kessel.inventory" +
      ".v1.GetReadyzRequest\032&.kessel.inventory." +
      "v1.GetReadyzResponse\" \202\323\344\223\002\032\022\030/api/inven" +
      "tory/v1/readyzBh\n#org.project_kessel.api" +
      ".inventory.v1P\001Z?github.com/project-kess" +
      "el/inventory-api/api/kessel/inventory/v1" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_kessel_inventory_v1_GetLivezRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kessel_inventory_v1_GetLivezRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_kessel_inventory_v1_GetLivezRequest_descriptor,
        new java.lang.String[] { });
    internal_static_kessel_inventory_v1_GetLivezResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kessel_inventory_v1_GetLivezResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_kessel_inventory_v1_GetLivezResponse_descriptor,
        new java.lang.String[] { "Status", "Code", });
    internal_static_kessel_inventory_v1_GetReadyzRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_kessel_inventory_v1_GetReadyzRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_kessel_inventory_v1_GetReadyzRequest_descriptor,
        new java.lang.String[] { });
    internal_static_kessel_inventory_v1_GetReadyzResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_kessel_inventory_v1_GetReadyzResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_kessel_inventory_v1_GetReadyzResponse_descriptor,
        new java.lang.String[] { "Status", "Code", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
