// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta1/resources/k8s_policies_service.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta1.resources;

@com.google.protobuf.Generated
public interface CreateK8sPolicyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta1.resources.CreateK8sPolicyResponse)
    com.google.protobuf.MessageOrBuilder {
}
