// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta1/resources/k8s_cluster_detail.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta1.resources;

/**
 * Protobuf type {@code kessel.inventory.v1beta1.resources.K8sClusterDetail}
 */
@com.google.protobuf.Generated
public final class K8sClusterDetail extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:kessel.inventory.v1beta1.resources.K8sClusterDetail)
    K8sClusterDetailOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      K8sClusterDetail.class.getName());
  }
  // Use K8sClusterDetail.newBuilder() to construct.
  private K8sClusterDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private K8sClusterDetail() {
    externalClusterId_ = "";
    clusterStatus_ = 0;
    clusterReason_ = "";
    kubeVersion_ = "";
    kubeVendor_ = 0;
    vendorVersion_ = "";
    cloudPlatform_ = 0;
    nodes_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailProto.internal_static_kessel_inventory_v1beta1_resources_K8sClusterDetail_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailProto.internal_static_kessel_inventory_v1beta1_resources_K8sClusterDetail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.class, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.Builder.class);
  }

  /**
   * <pre>
   * the aggregate status of the cluster
   * </pre>
   *
   * Protobuf enum {@code kessel.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus}
   */
  public enum ClusterStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CLUSTER_STATUS_UNSPECIFIED = 0;</code>
     */
    CLUSTER_STATUS_UNSPECIFIED(0),
    /**
     * <code>CLUSTER_STATUS_OTHER = 1;</code>
     */
    CLUSTER_STATUS_OTHER(1),
    /**
     * <code>READY = 2;</code>
     */
    READY(2),
    /**
     * <code>FAILED = 3;</code>
     */
    FAILED(3),
    /**
     * <code>OFFLINE = 4;</code>
     */
    OFFLINE(4),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        ClusterStatus.class.getName());
    }
    /**
     * <code>CLUSTER_STATUS_UNSPECIFIED = 0;</code>
     */
    public static final int CLUSTER_STATUS_UNSPECIFIED_VALUE = 0;
    /**
     * <code>CLUSTER_STATUS_OTHER = 1;</code>
     */
    public static final int CLUSTER_STATUS_OTHER_VALUE = 1;
    /**
     * <code>READY = 2;</code>
     */
    public static final int READY_VALUE = 2;
    /**
     * <code>FAILED = 3;</code>
     */
    public static final int FAILED_VALUE = 3;
    /**
     * <code>OFFLINE = 4;</code>
     */
    public static final int OFFLINE_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ClusterStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ClusterStatus forNumber(int value) {
      switch (value) {
        case 0: return CLUSTER_STATUS_UNSPECIFIED;
        case 1: return CLUSTER_STATUS_OTHER;
        case 2: return READY;
        case 3: return FAILED;
        case 4: return OFFLINE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ClusterStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ClusterStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ClusterStatus>() {
            public ClusterStatus findValueByNumber(int number) {
              return ClusterStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.getDescriptor().getEnumTypes().get(0);
    }

    private static final ClusterStatus[] VALUES = values();

    public static ClusterStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ClusterStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:kessel.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus)
  }

  /**
   * <pre>
   * The kubernetes vendor
   * </pre>
   *
   * Protobuf enum {@code kessel.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor}
   */
  public enum KubeVendor
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>KUBE_VENDOR_UNSPECIFIED = 0;</code>
     */
    KUBE_VENDOR_UNSPECIFIED(0),
    /**
     * <code>KUBE_VENDOR_OTHER = 1;</code>
     */
    KUBE_VENDOR_OTHER(1),
    /**
     * <code>AKS = 2;</code>
     */
    AKS(2),
    /**
     * <code>EKS = 3;</code>
     */
    EKS(3),
    /**
     * <code>IKS = 4;</code>
     */
    IKS(4),
    /**
     * <code>OPENSHIFT = 5;</code>
     */
    OPENSHIFT(5),
    /**
     * <code>GKE = 6;</code>
     */
    GKE(6),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        KubeVendor.class.getName());
    }
    /**
     * <code>KUBE_VENDOR_UNSPECIFIED = 0;</code>
     */
    public static final int KUBE_VENDOR_UNSPECIFIED_VALUE = 0;
    /**
     * <code>KUBE_VENDOR_OTHER = 1;</code>
     */
    public static final int KUBE_VENDOR_OTHER_VALUE = 1;
    /**
     * <code>AKS = 2;</code>
     */
    public static final int AKS_VALUE = 2;
    /**
     * <code>EKS = 3;</code>
     */
    public static final int EKS_VALUE = 3;
    /**
     * <code>IKS = 4;</code>
     */
    public static final int IKS_VALUE = 4;
    /**
     * <code>OPENSHIFT = 5;</code>
     */
    public static final int OPENSHIFT_VALUE = 5;
    /**
     * <code>GKE = 6;</code>
     */
    public static final int GKE_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static KubeVendor valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static KubeVendor forNumber(int value) {
      switch (value) {
        case 0: return KUBE_VENDOR_UNSPECIFIED;
        case 1: return KUBE_VENDOR_OTHER;
        case 2: return AKS;
        case 3: return EKS;
        case 4: return IKS;
        case 5: return OPENSHIFT;
        case 6: return GKE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<KubeVendor>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        KubeVendor> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<KubeVendor>() {
            public KubeVendor findValueByNumber(int number) {
              return KubeVendor.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.getDescriptor().getEnumTypes().get(1);
    }

    private static final KubeVendor[] VALUES = values();

    public static KubeVendor valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private KubeVendor(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:kessel.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor)
  }

  /**
   * <pre>
   * The platform on which this cluster is hosted
   * </pre>
   *
   * Protobuf enum {@code kessel.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform}
   */
  public enum CloudPlatform
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CLOUD_PLATFORM_UNSPECIFIED = 0;</code>
     */
    CLOUD_PLATFORM_UNSPECIFIED(0),
    /**
     * <code>CLOUD_PLATFORM_OTHER = 1;</code>
     */
    CLOUD_PLATFORM_OTHER(1),
    /**
     * <code>NONE_UPI = 2;</code>
     */
    NONE_UPI(2),
    /**
     * <code>BAREMETAL_IPI = 3;</code>
     */
    BAREMETAL_IPI(3),
    /**
     * <code>BAREMETAL_UPI = 4;</code>
     */
    BAREMETAL_UPI(4),
    /**
     * <code>AWS_IPI = 5;</code>
     */
    AWS_IPI(5),
    /**
     * <code>AWS_UPI = 6;</code>
     */
    AWS_UPI(6),
    /**
     * <code>AZURE_IPI = 7;</code>
     */
    AZURE_IPI(7),
    /**
     * <code>AZURE_UPI = 8;</code>
     */
    AZURE_UPI(8),
    /**
     * <code>IBMCLOUD_IPI = 9;</code>
     */
    IBMCLOUD_IPI(9),
    /**
     * <code>IBMCLOUD_UPI = 10;</code>
     */
    IBMCLOUD_UPI(10),
    /**
     * <code>KUBEVIRT_IPI = 11;</code>
     */
    KUBEVIRT_IPI(11),
    /**
     * <code>OPENSTACK_IPI = 12;</code>
     */
    OPENSTACK_IPI(12),
    /**
     * <code>OPENSTACK_UPI = 13;</code>
     */
    OPENSTACK_UPI(13),
    /**
     * <code>GCP_IPI = 14;</code>
     */
    GCP_IPI(14),
    /**
     * <code>GCP_UPI = 15;</code>
     */
    GCP_UPI(15),
    /**
     * <code>NUTANIX_IPI = 16;</code>
     */
    NUTANIX_IPI(16),
    /**
     * <code>NUTANIX_UPI = 17;</code>
     */
    NUTANIX_UPI(17),
    /**
     * <code>VSPHERE_IPI = 18;</code>
     */
    VSPHERE_IPI(18),
    /**
     * <code>VSPHERE_UPI = 19;</code>
     */
    VSPHERE_UPI(19),
    /**
     * <code>OVIRT_IPI = 20;</code>
     */
    OVIRT_IPI(20),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        CloudPlatform.class.getName());
    }
    /**
     * <code>CLOUD_PLATFORM_UNSPECIFIED = 0;</code>
     */
    public static final int CLOUD_PLATFORM_UNSPECIFIED_VALUE = 0;
    /**
     * <code>CLOUD_PLATFORM_OTHER = 1;</code>
     */
    public static final int CLOUD_PLATFORM_OTHER_VALUE = 1;
    /**
     * <code>NONE_UPI = 2;</code>
     */
    public static final int NONE_UPI_VALUE = 2;
    /**
     * <code>BAREMETAL_IPI = 3;</code>
     */
    public static final int BAREMETAL_IPI_VALUE = 3;
    /**
     * <code>BAREMETAL_UPI = 4;</code>
     */
    public static final int BAREMETAL_UPI_VALUE = 4;
    /**
     * <code>AWS_IPI = 5;</code>
     */
    public static final int AWS_IPI_VALUE = 5;
    /**
     * <code>AWS_UPI = 6;</code>
     */
    public static final int AWS_UPI_VALUE = 6;
    /**
     * <code>AZURE_IPI = 7;</code>
     */
    public static final int AZURE_IPI_VALUE = 7;
    /**
     * <code>AZURE_UPI = 8;</code>
     */
    public static final int AZURE_UPI_VALUE = 8;
    /**
     * <code>IBMCLOUD_IPI = 9;</code>
     */
    public static final int IBMCLOUD_IPI_VALUE = 9;
    /**
     * <code>IBMCLOUD_UPI = 10;</code>
     */
    public static final int IBMCLOUD_UPI_VALUE = 10;
    /**
     * <code>KUBEVIRT_IPI = 11;</code>
     */
    public static final int KUBEVIRT_IPI_VALUE = 11;
    /**
     * <code>OPENSTACK_IPI = 12;</code>
     */
    public static final int OPENSTACK_IPI_VALUE = 12;
    /**
     * <code>OPENSTACK_UPI = 13;</code>
     */
    public static final int OPENSTACK_UPI_VALUE = 13;
    /**
     * <code>GCP_IPI = 14;</code>
     */
    public static final int GCP_IPI_VALUE = 14;
    /**
     * <code>GCP_UPI = 15;</code>
     */
    public static final int GCP_UPI_VALUE = 15;
    /**
     * <code>NUTANIX_IPI = 16;</code>
     */
    public static final int NUTANIX_IPI_VALUE = 16;
    /**
     * <code>NUTANIX_UPI = 17;</code>
     */
    public static final int NUTANIX_UPI_VALUE = 17;
    /**
     * <code>VSPHERE_IPI = 18;</code>
     */
    public static final int VSPHERE_IPI_VALUE = 18;
    /**
     * <code>VSPHERE_UPI = 19;</code>
     */
    public static final int VSPHERE_UPI_VALUE = 19;
    /**
     * <code>OVIRT_IPI = 20;</code>
     */
    public static final int OVIRT_IPI_VALUE = 20;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CloudPlatform valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CloudPlatform forNumber(int value) {
      switch (value) {
        case 0: return CLOUD_PLATFORM_UNSPECIFIED;
        case 1: return CLOUD_PLATFORM_OTHER;
        case 2: return NONE_UPI;
        case 3: return BAREMETAL_IPI;
        case 4: return BAREMETAL_UPI;
        case 5: return AWS_IPI;
        case 6: return AWS_UPI;
        case 7: return AZURE_IPI;
        case 8: return AZURE_UPI;
        case 9: return IBMCLOUD_IPI;
        case 10: return IBMCLOUD_UPI;
        case 11: return KUBEVIRT_IPI;
        case 12: return OPENSTACK_IPI;
        case 13: return OPENSTACK_UPI;
        case 14: return GCP_IPI;
        case 15: return GCP_UPI;
        case 16: return NUTANIX_IPI;
        case 17: return NUTANIX_UPI;
        case 18: return VSPHERE_IPI;
        case 19: return VSPHERE_UPI;
        case 20: return OVIRT_IPI;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CloudPlatform>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CloudPlatform> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CloudPlatform>() {
            public CloudPlatform findValueByNumber(int number) {
              return CloudPlatform.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.getDescriptor().getEnumTypes().get(2);
    }

    private static final CloudPlatform[] VALUES = values();

    public static CloudPlatform valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CloudPlatform(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:kessel.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform)
  }

  private int bitField0_;
  public static final int EXTERNAL_CLUSTER_ID_FIELD_NUMBER = 219571597;
  @SuppressWarnings("serial")
  private volatile java.lang.Object externalClusterId_ = "";
  /**
   * <pre>
   * The OCP cluster ID or ARN etc for *KS
   * </pre>
   *
   * <code>string external_cluster_id = 219571597 [json_name = "external_cluster_id", (.buf.validate.field) = { ... }</code>
   * @return The externalClusterId.
   */
  @java.lang.Override
  public java.lang.String getExternalClusterId() {
    java.lang.Object ref = externalClusterId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      externalClusterId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The OCP cluster ID or ARN etc for *KS
   * </pre>
   *
   * <code>string external_cluster_id = 219571597 [json_name = "external_cluster_id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for externalClusterId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExternalClusterIdBytes() {
    java.lang.Object ref = externalClusterId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      externalClusterId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLUSTER_STATUS_FIELD_NUMBER = 499346904;
  private int clusterStatus_ = 0;
  /**
   * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus cluster_status = 499346904 [json_name = "cluster_status", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for clusterStatus.
   */
  @java.lang.Override public int getClusterStatusValue() {
    return clusterStatus_;
  }
  /**
   * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus cluster_status = 499346904 [json_name = "cluster_status", (.buf.validate.field) = { ... }</code>
   * @return The clusterStatus.
   */
  @java.lang.Override public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus getClusterStatus() {
    org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus result = org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus.forNumber(clusterStatus_);
    return result == null ? org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus.UNRECOGNIZED : result;
  }

  public static final int CLUSTER_REASON_FIELD_NUMBER = 499346905;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clusterReason_ = "";
  /**
   * <code>optional string cluster_reason = 499346905 [json_name = "cluster_reason", (.buf.validate.field) = { ... }</code>
   * @return Whether the clusterReason field is set.
   */
  @java.lang.Override
  public boolean hasClusterReason() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string cluster_reason = 499346905 [json_name = "cluster_reason", (.buf.validate.field) = { ... }</code>
   * @return The clusterReason.
   */
  @java.lang.Override
  public java.lang.String getClusterReason() {
    java.lang.Object ref = clusterReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clusterReason_ = s;
      return s;
    }
  }
  /**
   * <code>optional string cluster_reason = 499346905 [json_name = "cluster_reason", (.buf.validate.field) = { ... }</code>
   * @return The bytes for clusterReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClusterReasonBytes() {
    java.lang.Object ref = clusterReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clusterReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KUBE_VERSION_FIELD_NUMBER = 395858490;
  @SuppressWarnings("serial")
  private volatile java.lang.Object kubeVersion_ = "";
  /**
   * <pre>
   * The version of kubernetes
   * </pre>
   *
   * <code>string kube_version = 395858490 [json_name = "kube_version"];</code>
   * @return The kubeVersion.
   */
  @java.lang.Override
  public java.lang.String getKubeVersion() {
    java.lang.Object ref = kubeVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      kubeVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The version of kubernetes
   * </pre>
   *
   * <code>string kube_version = 395858490 [json_name = "kube_version"];</code>
   * @return The bytes for kubeVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKubeVersionBytes() {
    java.lang.Object ref = kubeVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      kubeVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KUBE_VENDOR_FIELD_NUMBER = 264191642;
  private int kubeVendor_ = 0;
  /**
   * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor kube_vendor = 264191642 [json_name = "kube_vendor", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for kubeVendor.
   */
  @java.lang.Override public int getKubeVendorValue() {
    return kubeVendor_;
  }
  /**
   * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor kube_vendor = 264191642 [json_name = "kube_vendor", (.buf.validate.field) = { ... }</code>
   * @return The kubeVendor.
   */
  @java.lang.Override public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor getKubeVendor() {
    org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor result = org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor.forNumber(kubeVendor_);
    return result == null ? org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor.UNRECOGNIZED : result;
  }

  public static final int VENDOR_VERSION_FIELD_NUMBER = 23961827;
  @SuppressWarnings("serial")
  private volatile java.lang.Object vendorVersion_ = "";
  /**
   * <pre>
   * The version of the productized kubernetes distribution
   * </pre>
   *
   * <code>string vendor_version = 23961827 [json_name = "vendor_version", (.buf.validate.field) = { ... }</code>
   * @return The vendorVersion.
   */
  @java.lang.Override
  public java.lang.String getVendorVersion() {
    java.lang.Object ref = vendorVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vendorVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The version of the productized kubernetes distribution
   * </pre>
   *
   * <code>string vendor_version = 23961827 [json_name = "vendor_version", (.buf.validate.field) = { ... }</code>
   * @return The bytes for vendorVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVendorVersionBytes() {
    java.lang.Object ref = vendorVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      vendorVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLOUD_PLATFORM_FIELD_NUMBER = 476768062;
  private int cloudPlatform_ = 0;
  /**
   * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform cloud_platform = 476768062 [json_name = "cloud_platform", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for cloudPlatform.
   */
  @java.lang.Override public int getCloudPlatformValue() {
    return cloudPlatform_;
  }
  /**
   * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform cloud_platform = 476768062 [json_name = "cloud_platform", (.buf.validate.field) = { ... }</code>
   * @return The cloudPlatform.
   */
  @java.lang.Override public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform getCloudPlatform() {
    org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform result = org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform.forNumber(cloudPlatform_);
    return result == null ? org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform.UNRECOGNIZED : result;
  }

  public static final int NODES_FIELD_NUMBER = 75440785;
  @SuppressWarnings("serial")
  private java.util.List<org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner> nodes_;
  /**
   * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
   */
  @java.lang.Override
  public java.util.List<org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner> getNodesList() {
    return nodes_;
  }
  /**
   * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerOrBuilder> 
      getNodesOrBuilderList() {
    return nodes_;
  }
  /**
   * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
   */
  @java.lang.Override
  public int getNodesCount() {
    return nodes_.size();
  }
  /**
   * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
   */
  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner getNodes(int index) {
    return nodes_.get(index);
  }
  /**
   * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
   */
  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerOrBuilder getNodesOrBuilder(
      int index) {
    return nodes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(vendorVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 23961827, vendorVersion_);
    }
    for (int i = 0; i < nodes_.size(); i++) {
      output.writeMessage(75440785, nodes_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(externalClusterId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 219571597, externalClusterId_);
    }
    if (kubeVendor_ != org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor.KUBE_VENDOR_UNSPECIFIED.getNumber()) {
      output.writeEnum(264191642, kubeVendor_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(kubeVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 395858490, kubeVersion_);
    }
    if (cloudPlatform_ != org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform.CLOUD_PLATFORM_UNSPECIFIED.getNumber()) {
      output.writeEnum(476768062, cloudPlatform_);
    }
    if (clusterStatus_ != org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus.CLUSTER_STATUS_UNSPECIFIED.getNumber()) {
      output.writeEnum(499346904, clusterStatus_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 499346905, clusterReason_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(vendorVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(23961827, vendorVersion_);
    }
    for (int i = 0; i < nodes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(75440785, nodes_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(externalClusterId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(219571597, externalClusterId_);
    }
    if (kubeVendor_ != org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor.KUBE_VENDOR_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(264191642, kubeVendor_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(kubeVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(395858490, kubeVersion_);
    }
    if (cloudPlatform_ != org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform.CLOUD_PLATFORM_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(476768062, cloudPlatform_);
    }
    if (clusterStatus_ != org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus.CLUSTER_STATUS_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(499346904, clusterStatus_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(499346905, clusterReason_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail)) {
      return super.equals(obj);
    }
    org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail other = (org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail) obj;

    if (!getExternalClusterId()
        .equals(other.getExternalClusterId())) return false;
    if (clusterStatus_ != other.clusterStatus_) return false;
    if (hasClusterReason() != other.hasClusterReason()) return false;
    if (hasClusterReason()) {
      if (!getClusterReason()
          .equals(other.getClusterReason())) return false;
    }
    if (!getKubeVersion()
        .equals(other.getKubeVersion())) return false;
    if (kubeVendor_ != other.kubeVendor_) return false;
    if (!getVendorVersion()
        .equals(other.getVendorVersion())) return false;
    if (cloudPlatform_ != other.cloudPlatform_) return false;
    if (!getNodesList()
        .equals(other.getNodesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXTERNAL_CLUSTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getExternalClusterId().hashCode();
    hash = (37 * hash) + CLUSTER_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + clusterStatus_;
    if (hasClusterReason()) {
      hash = (37 * hash) + CLUSTER_REASON_FIELD_NUMBER;
      hash = (53 * hash) + getClusterReason().hashCode();
    }
    hash = (37 * hash) + KUBE_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getKubeVersion().hashCode();
    hash = (37 * hash) + KUBE_VENDOR_FIELD_NUMBER;
    hash = (53 * hash) + kubeVendor_;
    hash = (37 * hash) + VENDOR_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVendorVersion().hashCode();
    hash = (37 * hash) + CLOUD_PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + cloudPlatform_;
    if (getNodesCount() > 0) {
      hash = (37 * hash) + NODES_FIELD_NUMBER;
      hash = (53 * hash) + getNodesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kessel.inventory.v1beta1.resources.K8sClusterDetail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kessel.inventory.v1beta1.resources.K8sClusterDetail)
      org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailProto.internal_static_kessel_inventory_v1beta1_resources_K8sClusterDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailProto.internal_static_kessel_inventory_v1beta1_resources_K8sClusterDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.class, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.Builder.class);
    }

    // Construct using org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      externalClusterId_ = "";
      clusterStatus_ = 0;
      clusterReason_ = "";
      kubeVersion_ = "";
      kubeVendor_ = 0;
      vendorVersion_ = "";
      cloudPlatform_ = 0;
      if (nodesBuilder_ == null) {
        nodes_ = java.util.Collections.emptyList();
      } else {
        nodes_ = null;
        nodesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailProto.internal_static_kessel_inventory_v1beta1_resources_K8sClusterDetail_descriptor;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail getDefaultInstanceForType() {
      return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.getDefaultInstance();
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail build() {
      org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail buildPartial() {
      org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail result = new org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail result) {
      if (nodesBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          nodes_ = java.util.Collections.unmodifiableList(nodes_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.nodes_ = nodes_;
      } else {
        result.nodes_ = nodesBuilder_.build();
      }
    }

    private void buildPartial0(org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.externalClusterId_ = externalClusterId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.clusterStatus_ = clusterStatus_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.clusterReason_ = clusterReason_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.kubeVersion_ = kubeVersion_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.kubeVendor_ = kubeVendor_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.vendorVersion_ = vendorVersion_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.cloudPlatform_ = cloudPlatform_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail) {
        return mergeFrom((org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail other) {
      if (other == org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.getDefaultInstance()) return this;
      if (!other.getExternalClusterId().isEmpty()) {
        externalClusterId_ = other.externalClusterId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.clusterStatus_ != 0) {
        setClusterStatusValue(other.getClusterStatusValue());
      }
      if (other.hasClusterReason()) {
        clusterReason_ = other.clusterReason_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getKubeVersion().isEmpty()) {
        kubeVersion_ = other.kubeVersion_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.kubeVendor_ != 0) {
        setKubeVendorValue(other.getKubeVendorValue());
      }
      if (!other.getVendorVersion().isEmpty()) {
        vendorVersion_ = other.vendorVersion_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.cloudPlatform_ != 0) {
        setCloudPlatformValue(other.getCloudPlatformValue());
      }
      if (nodesBuilder_ == null) {
        if (!other.nodes_.isEmpty()) {
          if (nodes_.isEmpty()) {
            nodes_ = other.nodes_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureNodesIsMutable();
            nodes_.addAll(other.nodes_);
          }
          onChanged();
        }
      } else {
        if (!other.nodes_.isEmpty()) {
          if (nodesBuilder_.isEmpty()) {
            nodesBuilder_.dispose();
            nodesBuilder_ = null;
            nodes_ = other.nodes_;
            bitField0_ = (bitField0_ & ~0x00000080);
            nodesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetNodesFieldBuilder() : null;
          } else {
            nodesBuilder_.addAllMessages(other.nodes_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 191694618: {
              vendorVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 191694618
            case 603526282: {
              org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner m =
                  input.readMessage(
                      org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.parser(),
                      extensionRegistry);
              if (nodesBuilder_ == null) {
                ensureNodesIsMutable();
                nodes_.add(m);
              } else {
                nodesBuilder_.addMessage(m);
              }
              break;
            } // case 603526282
            case 1756572778: {
              externalClusterId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 1756572778
            case 2113533136: {
              kubeVendor_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 2113533136
            case -1128099374: {
              kubeVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case -1128099374
            case -480822800: {
              cloudPlatform_ = input.readEnum();
              bitField0_ |= 0x00000040;
              break;
            } // case -480822800
            case -300192064: {
              clusterStatus_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case -300192064
            case -300192054: {
              clusterReason_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case -300192054
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object externalClusterId_ = "";
    /**
     * <pre>
     * The OCP cluster ID or ARN etc for *KS
     * </pre>
     *
     * <code>string external_cluster_id = 219571597 [json_name = "external_cluster_id", (.buf.validate.field) = { ... }</code>
     * @return The externalClusterId.
     */
    public java.lang.String getExternalClusterId() {
      java.lang.Object ref = externalClusterId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalClusterId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The OCP cluster ID or ARN etc for *KS
     * </pre>
     *
     * <code>string external_cluster_id = 219571597 [json_name = "external_cluster_id", (.buf.validate.field) = { ... }</code>
     * @return The bytes for externalClusterId.
     */
    public com.google.protobuf.ByteString
        getExternalClusterIdBytes() {
      java.lang.Object ref = externalClusterId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalClusterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The OCP cluster ID or ARN etc for *KS
     * </pre>
     *
     * <code>string external_cluster_id = 219571597 [json_name = "external_cluster_id", (.buf.validate.field) = { ... }</code>
     * @param value The externalClusterId to set.
     * @return This builder for chaining.
     */
    public Builder setExternalClusterId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      externalClusterId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The OCP cluster ID or ARN etc for *KS
     * </pre>
     *
     * <code>string external_cluster_id = 219571597 [json_name = "external_cluster_id", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearExternalClusterId() {
      externalClusterId_ = getDefaultInstance().getExternalClusterId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The OCP cluster ID or ARN etc for *KS
     * </pre>
     *
     * <code>string external_cluster_id = 219571597 [json_name = "external_cluster_id", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for externalClusterId to set.
     * @return This builder for chaining.
     */
    public Builder setExternalClusterIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      externalClusterId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int clusterStatus_ = 0;
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus cluster_status = 499346904 [json_name = "cluster_status", (.buf.validate.field) = { ... }</code>
     * @return The enum numeric value on the wire for clusterStatus.
     */
    @java.lang.Override public int getClusterStatusValue() {
      return clusterStatus_;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus cluster_status = 499346904 [json_name = "cluster_status", (.buf.validate.field) = { ... }</code>
     * @param value The enum numeric value on the wire for clusterStatus to set.
     * @return This builder for chaining.
     */
    public Builder setClusterStatusValue(int value) {
      clusterStatus_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus cluster_status = 499346904 [json_name = "cluster_status", (.buf.validate.field) = { ... }</code>
     * @return The clusterStatus.
     */
    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus getClusterStatus() {
      org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus result = org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus.forNumber(clusterStatus_);
      return result == null ? org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus cluster_status = 499346904 [json_name = "cluster_status", (.buf.validate.field) = { ... }</code>
     * @param value The clusterStatus to set.
     * @return This builder for chaining.
     */
    public Builder setClusterStatus(org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      clusterStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus cluster_status = 499346904 [json_name = "cluster_status", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearClusterStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      clusterStatus_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object clusterReason_ = "";
    /**
     * <code>optional string cluster_reason = 499346905 [json_name = "cluster_reason", (.buf.validate.field) = { ... }</code>
     * @return Whether the clusterReason field is set.
     */
    public boolean hasClusterReason() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string cluster_reason = 499346905 [json_name = "cluster_reason", (.buf.validate.field) = { ... }</code>
     * @return The clusterReason.
     */
    public java.lang.String getClusterReason() {
      java.lang.Object ref = clusterReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clusterReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string cluster_reason = 499346905 [json_name = "cluster_reason", (.buf.validate.field) = { ... }</code>
     * @return The bytes for clusterReason.
     */
    public com.google.protobuf.ByteString
        getClusterReasonBytes() {
      java.lang.Object ref = clusterReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusterReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string cluster_reason = 499346905 [json_name = "cluster_reason", (.buf.validate.field) = { ... }</code>
     * @param value The clusterReason to set.
     * @return This builder for chaining.
     */
    public Builder setClusterReason(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clusterReason_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string cluster_reason = 499346905 [json_name = "cluster_reason", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearClusterReason() {
      clusterReason_ = getDefaultInstance().getClusterReason();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string cluster_reason = 499346905 [json_name = "cluster_reason", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for clusterReason to set.
     * @return This builder for chaining.
     */
    public Builder setClusterReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clusterReason_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object kubeVersion_ = "";
    /**
     * <pre>
     * The version of kubernetes
     * </pre>
     *
     * <code>string kube_version = 395858490 [json_name = "kube_version"];</code>
     * @return The kubeVersion.
     */
    public java.lang.String getKubeVersion() {
      java.lang.Object ref = kubeVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kubeVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The version of kubernetes
     * </pre>
     *
     * <code>string kube_version = 395858490 [json_name = "kube_version"];</code>
     * @return The bytes for kubeVersion.
     */
    public com.google.protobuf.ByteString
        getKubeVersionBytes() {
      java.lang.Object ref = kubeVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kubeVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The version of kubernetes
     * </pre>
     *
     * <code>string kube_version = 395858490 [json_name = "kube_version"];</code>
     * @param value The kubeVersion to set.
     * @return This builder for chaining.
     */
    public Builder setKubeVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      kubeVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The version of kubernetes
     * </pre>
     *
     * <code>string kube_version = 395858490 [json_name = "kube_version"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKubeVersion() {
      kubeVersion_ = getDefaultInstance().getKubeVersion();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The version of kubernetes
     * </pre>
     *
     * <code>string kube_version = 395858490 [json_name = "kube_version"];</code>
     * @param value The bytes for kubeVersion to set.
     * @return This builder for chaining.
     */
    public Builder setKubeVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      kubeVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int kubeVendor_ = 0;
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor kube_vendor = 264191642 [json_name = "kube_vendor", (.buf.validate.field) = { ... }</code>
     * @return The enum numeric value on the wire for kubeVendor.
     */
    @java.lang.Override public int getKubeVendorValue() {
      return kubeVendor_;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor kube_vendor = 264191642 [json_name = "kube_vendor", (.buf.validate.field) = { ... }</code>
     * @param value The enum numeric value on the wire for kubeVendor to set.
     * @return This builder for chaining.
     */
    public Builder setKubeVendorValue(int value) {
      kubeVendor_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor kube_vendor = 264191642 [json_name = "kube_vendor", (.buf.validate.field) = { ... }</code>
     * @return The kubeVendor.
     */
    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor getKubeVendor() {
      org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor result = org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor.forNumber(kubeVendor_);
      return result == null ? org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor.UNRECOGNIZED : result;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor kube_vendor = 264191642 [json_name = "kube_vendor", (.buf.validate.field) = { ... }</code>
     * @param value The kubeVendor to set.
     * @return This builder for chaining.
     */
    public Builder setKubeVendor(org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000010;
      kubeVendor_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor kube_vendor = 264191642 [json_name = "kube_vendor", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearKubeVendor() {
      bitField0_ = (bitField0_ & ~0x00000010);
      kubeVendor_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object vendorVersion_ = "";
    /**
     * <pre>
     * The version of the productized kubernetes distribution
     * </pre>
     *
     * <code>string vendor_version = 23961827 [json_name = "vendor_version", (.buf.validate.field) = { ... }</code>
     * @return The vendorVersion.
     */
    public java.lang.String getVendorVersion() {
      java.lang.Object ref = vendorVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vendorVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The version of the productized kubernetes distribution
     * </pre>
     *
     * <code>string vendor_version = 23961827 [json_name = "vendor_version", (.buf.validate.field) = { ... }</code>
     * @return The bytes for vendorVersion.
     */
    public com.google.protobuf.ByteString
        getVendorVersionBytes() {
      java.lang.Object ref = vendorVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vendorVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The version of the productized kubernetes distribution
     * </pre>
     *
     * <code>string vendor_version = 23961827 [json_name = "vendor_version", (.buf.validate.field) = { ... }</code>
     * @param value The vendorVersion to set.
     * @return This builder for chaining.
     */
    public Builder setVendorVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      vendorVersion_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The version of the productized kubernetes distribution
     * </pre>
     *
     * <code>string vendor_version = 23961827 [json_name = "vendor_version", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearVendorVersion() {
      vendorVersion_ = getDefaultInstance().getVendorVersion();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The version of the productized kubernetes distribution
     * </pre>
     *
     * <code>string vendor_version = 23961827 [json_name = "vendor_version", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for vendorVersion to set.
     * @return This builder for chaining.
     */
    public Builder setVendorVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      vendorVersion_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private int cloudPlatform_ = 0;
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform cloud_platform = 476768062 [json_name = "cloud_platform", (.buf.validate.field) = { ... }</code>
     * @return The enum numeric value on the wire for cloudPlatform.
     */
    @java.lang.Override public int getCloudPlatformValue() {
      return cloudPlatform_;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform cloud_platform = 476768062 [json_name = "cloud_platform", (.buf.validate.field) = { ... }</code>
     * @param value The enum numeric value on the wire for cloudPlatform to set.
     * @return This builder for chaining.
     */
    public Builder setCloudPlatformValue(int value) {
      cloudPlatform_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform cloud_platform = 476768062 [json_name = "cloud_platform", (.buf.validate.field) = { ... }</code>
     * @return The cloudPlatform.
     */
    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform getCloudPlatform() {
      org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform result = org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform.forNumber(cloudPlatform_);
      return result == null ? org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform.UNRECOGNIZED : result;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform cloud_platform = 476768062 [json_name = "cloud_platform", (.buf.validate.field) = { ... }</code>
     * @param value The cloudPlatform to set.
     * @return This builder for chaining.
     */
    public Builder setCloudPlatform(org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000040;
      cloudPlatform_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform cloud_platform = 476768062 [json_name = "cloud_platform", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearCloudPlatform() {
      bitField0_ = (bitField0_ & ~0x00000040);
      cloudPlatform_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner> nodes_ =
      java.util.Collections.emptyList();
    private void ensureNodesIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        nodes_ = new java.util.ArrayList<org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner>(nodes_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.Builder, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerOrBuilder> nodesBuilder_;

    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public java.util.List<org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner> getNodesList() {
      if (nodesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(nodes_);
      } else {
        return nodesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public int getNodesCount() {
      if (nodesBuilder_ == null) {
        return nodes_.size();
      } else {
        return nodesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner getNodes(int index) {
      if (nodesBuilder_ == null) {
        return nodes_.get(index);
      } else {
        return nodesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public Builder setNodes(
        int index, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.set(index, value);
        onChanged();
      } else {
        nodesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public Builder setNodes(
        int index, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.set(index, builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public Builder addNodes(org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.add(value);
        onChanged();
      } else {
        nodesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public Builder addNodes(
        int index, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner value) {
      if (nodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodesIsMutable();
        nodes_.add(index, value);
        onChanged();
      } else {
        nodesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public Builder addNodes(
        org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.add(builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public Builder addNodes(
        int index, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.Builder builderForValue) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.add(index, builderForValue.build());
        onChanged();
      } else {
        nodesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public Builder addAllNodes(
        java.lang.Iterable<? extends org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner> values) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nodes_);
        onChanged();
      } else {
        nodesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public Builder clearNodes() {
      if (nodesBuilder_ == null) {
        nodes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        nodesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public Builder removeNodes(int index) {
      if (nodesBuilder_ == null) {
        ensureNodesIsMutable();
        nodes_.remove(index);
        onChanged();
      } else {
        nodesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.Builder getNodesBuilder(
        int index) {
      return internalGetNodesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerOrBuilder getNodesOrBuilder(
        int index) {
      if (nodesBuilder_ == null) {
        return nodes_.get(index);  } else {
        return nodesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public java.util.List<? extends org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerOrBuilder> 
         getNodesOrBuilderList() {
      if (nodesBuilder_ != null) {
        return nodesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(nodes_);
      }
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.Builder addNodesBuilder() {
      return internalGetNodesFieldBuilder().addBuilder(
          org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.getDefaultInstance());
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.Builder addNodesBuilder(
        int index) {
      return internalGetNodesFieldBuilder().addBuilder(
          index, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.getDefaultInstance());
    }
    /**
     * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
     */
    public java.util.List<org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.Builder> 
         getNodesBuilderList() {
      return internalGetNodesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.Builder, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerOrBuilder> 
        internalGetNodesFieldBuilder() {
      if (nodesBuilder_ == null) {
        nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.Builder, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerOrBuilder>(
                nodes_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        nodes_ = null;
      }
      return nodesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:kessel.inventory.v1beta1.resources.K8sClusterDetail)
  }

  // @@protoc_insertion_point(class_scope:kessel.inventory.v1beta1.resources.K8sClusterDetail)
  private static final org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail();
  }

  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<K8sClusterDetail>
      PARSER = new com.google.protobuf.AbstractParser<K8sClusterDetail>() {
    @java.lang.Override
    public K8sClusterDetail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<K8sClusterDetail> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<K8sClusterDetail> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

