// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta1/resources/k8s_cluster_detail_nodes_inner.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta1.resources;

/**
 * Protobuf type {@code kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner}
 */
@com.google.protobuf.Generated
public final class K8sClusterDetailNodesInner extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner)
    K8sClusterDetailNodesInnerOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      K8sClusterDetailNodesInner.class.getName());
  }
  // Use K8sClusterDetailNodesInner.newBuilder() to construct.
  private K8sClusterDetailNodesInner(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private K8sClusterDetailNodesInner() {
    name_ = "";
    cpu_ = "";
    memory_ = "";
    labels_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerProto.internal_static_kessel_inventory_v1beta1_resources_K8sClusterDetailNodesInner_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerProto.internal_static_kessel_inventory_v1beta1_resources_K8sClusterDetailNodesInner_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.class, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 3373707;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <pre>
   * The name of the node (this can contain private info)
   * </pre>
   *
   * <code>string name = 3373707 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The name of the node (this can contain private info)
   * </pre>
   *
   * <code>string name = 3373707 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CPU_FIELD_NUMBER = 98728;
  @SuppressWarnings("serial")
  private volatile java.lang.Object cpu_ = "";
  /**
   * <pre>
   * CPU Capacity of the node defined in CPU units, e.g. &#92;"0.5&#92;"
   * </pre>
   *
   * <code>string cpu = 98728 [json_name = "cpu", (.buf.validate.field) = { ... }</code>
   * @return The cpu.
   */
  @java.lang.Override
  public java.lang.String getCpu() {
    java.lang.Object ref = cpu_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cpu_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * CPU Capacity of the node defined in CPU units, e.g. &#92;"0.5&#92;"
   * </pre>
   *
   * <code>string cpu = 98728 [json_name = "cpu", (.buf.validate.field) = { ... }</code>
   * @return The bytes for cpu.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCpuBytes() {
    java.lang.Object ref = cpu_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cpu_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MEMORY_FIELD_NUMBER = 4014849;
  @SuppressWarnings("serial")
  private volatile java.lang.Object memory_ = "";
  /**
   * <pre>
   * Memory Capacity of the node defined as MiB, e.g. &#92;"50Mi&#92;"
   * </pre>
   *
   * <code>string memory = 4014849 [json_name = "memory", (.buf.validate.field) = { ... }</code>
   * @return The memory.
   */
  @java.lang.Override
  public java.lang.String getMemory() {
    java.lang.Object ref = memory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      memory_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Memory Capacity of the node defined as MiB, e.g. &#92;"50Mi&#92;"
   * </pre>
   *
   * <code>string memory = 4014849 [json_name = "memory", (.buf.validate.field) = { ... }</code>
   * @return The bytes for memory.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMemoryBytes() {
    java.lang.Object ref = memory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      memory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LABELS_FIELD_NUMBER = 36675587;
  @SuppressWarnings("serial")
  private java.util.List<org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel> labels_;
  /**
   * <pre>
   * Map of string keys and string values that can be used to organize and
   * categorize (scope and select) resources
   * Todo: Do we require at least 1 label?
   * </pre>
   *
   * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public java.util.List<org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel> getLabelsList() {
    return labels_;
  }
  /**
   * <pre>
   * Map of string keys and string values that can be used to organize and
   * categorize (scope and select) resources
   * Todo: Do we require at least 1 label?
   * </pre>
   *
   * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.project_kessel.api.inventory.v1beta1.resources.ResourceLabelOrBuilder> 
      getLabelsOrBuilderList() {
    return labels_;
  }
  /**
   * <pre>
   * Map of string keys and string values that can be used to organize and
   * categorize (scope and select) resources
   * Todo: Do we require at least 1 label?
   * </pre>
   *
   * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public int getLabelsCount() {
    return labels_.size();
  }
  /**
   * <pre>
   * Map of string keys and string values that can be used to organize and
   * categorize (scope and select) resources
   * Todo: Do we require at least 1 label?
   * </pre>
   *
   * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel getLabels(int index) {
    return labels_.get(index);
  }
  /**
   * <pre>
   * Map of string keys and string values that can be used to organize and
   * categorize (scope and select) resources
   * Todo: Do we require at least 1 label?
   * </pre>
   *
   * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
   */
  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta1.resources.ResourceLabelOrBuilder getLabelsOrBuilder(
      int index) {
    return labels_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cpu_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 98728, cpu_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3373707, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(memory_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4014849, memory_);
    }
    for (int i = 0; i < labels_.size(); i++) {
      output.writeMessage(36675587, labels_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cpu_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(98728, cpu_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3373707, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(memory_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4014849, memory_);
    }
    for (int i = 0; i < labels_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(36675587, labels_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner)) {
      return super.equals(obj);
    }
    org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner other = (org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getCpu()
        .equals(other.getCpu())) return false;
    if (!getMemory()
        .equals(other.getMemory())) return false;
    if (!getLabelsList()
        .equals(other.getLabelsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CPU_FIELD_NUMBER;
    hash = (53 * hash) + getCpu().hashCode();
    hash = (37 * hash) + MEMORY_FIELD_NUMBER;
    hash = (53 * hash) + getMemory().hashCode();
    if (getLabelsCount() > 0) {
      hash = (37 * hash) + LABELS_FIELD_NUMBER;
      hash = (53 * hash) + getLabelsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner)
      org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerProto.internal_static_kessel_inventory_v1beta1_resources_K8sClusterDetailNodesInner_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerProto.internal_static_kessel_inventory_v1beta1_resources_K8sClusterDetailNodesInner_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.class, org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.Builder.class);
    }

    // Construct using org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      cpu_ = "";
      memory_ = "";
      if (labelsBuilder_ == null) {
        labels_ = java.util.Collections.emptyList();
      } else {
        labels_ = null;
        labelsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerProto.internal_static_kessel_inventory_v1beta1_resources_K8sClusterDetailNodesInner_descriptor;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner getDefaultInstanceForType() {
      return org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.getDefaultInstance();
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner build() {
      org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner buildPartial() {
      org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner result = new org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner result) {
      if (labelsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          labels_ = java.util.Collections.unmodifiableList(labels_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.labels_ = labels_;
      } else {
        result.labels_ = labelsBuilder_.build();
      }
    }

    private void buildPartial0(org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cpu_ = cpu_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.memory_ = memory_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner) {
        return mergeFrom((org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner other) {
      if (other == org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getCpu().isEmpty()) {
        cpu_ = other.cpu_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getMemory().isEmpty()) {
        memory_ = other.memory_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (labelsBuilder_ == null) {
        if (!other.labels_.isEmpty()) {
          if (labels_.isEmpty()) {
            labels_ = other.labels_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureLabelsIsMutable();
            labels_.addAll(other.labels_);
          }
          onChanged();
        }
      } else {
        if (!other.labels_.isEmpty()) {
          if (labelsBuilder_.isEmpty()) {
            labelsBuilder_.dispose();
            labelsBuilder_ = null;
            labels_ = other.labels_;
            bitField0_ = (bitField0_ & ~0x00000008);
            labelsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetLabelsFieldBuilder() : null;
          } else {
            labelsBuilder_.addAllMessages(other.labels_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 789826: {
              cpu_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 789826
            case 26989658: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 26989658
            case 32118794: {
              memory_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 32118794
            case 293404698: {
              org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel m =
                  input.readMessage(
                      org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel.parser(),
                      extensionRegistry);
              if (labelsBuilder_ == null) {
                ensureLabelsIsMutable();
                labels_.add(m);
              } else {
                labelsBuilder_.addMessage(m);
              }
              break;
            } // case 293404698
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * The name of the node (this can contain private info)
     * </pre>
     *
     * <code>string name = 3373707 [json_name = "name", (.buf.validate.field) = { ... }</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The name of the node (this can contain private info)
     * </pre>
     *
     * <code>string name = 3373707 [json_name = "name", (.buf.validate.field) = { ... }</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The name of the node (this can contain private info)
     * </pre>
     *
     * <code>string name = 3373707 [json_name = "name", (.buf.validate.field) = { ... }</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the node (this can contain private info)
     * </pre>
     *
     * <code>string name = 3373707 [json_name = "name", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name of the node (this can contain private info)
     * </pre>
     *
     * <code>string name = 3373707 [json_name = "name", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object cpu_ = "";
    /**
     * <pre>
     * CPU Capacity of the node defined in CPU units, e.g. &#92;"0.5&#92;"
     * </pre>
     *
     * <code>string cpu = 98728 [json_name = "cpu", (.buf.validate.field) = { ... }</code>
     * @return The cpu.
     */
    public java.lang.String getCpu() {
      java.lang.Object ref = cpu_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cpu_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * CPU Capacity of the node defined in CPU units, e.g. &#92;"0.5&#92;"
     * </pre>
     *
     * <code>string cpu = 98728 [json_name = "cpu", (.buf.validate.field) = { ... }</code>
     * @return The bytes for cpu.
     */
    public com.google.protobuf.ByteString
        getCpuBytes() {
      java.lang.Object ref = cpu_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpu_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * CPU Capacity of the node defined in CPU units, e.g. &#92;"0.5&#92;"
     * </pre>
     *
     * <code>string cpu = 98728 [json_name = "cpu", (.buf.validate.field) = { ... }</code>
     * @param value The cpu to set.
     * @return This builder for chaining.
     */
    public Builder setCpu(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      cpu_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * CPU Capacity of the node defined in CPU units, e.g. &#92;"0.5&#92;"
     * </pre>
     *
     * <code>string cpu = 98728 [json_name = "cpu", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearCpu() {
      cpu_ = getDefaultInstance().getCpu();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * CPU Capacity of the node defined in CPU units, e.g. &#92;"0.5&#92;"
     * </pre>
     *
     * <code>string cpu = 98728 [json_name = "cpu", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for cpu to set.
     * @return This builder for chaining.
     */
    public Builder setCpuBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      cpu_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object memory_ = "";
    /**
     * <pre>
     * Memory Capacity of the node defined as MiB, e.g. &#92;"50Mi&#92;"
     * </pre>
     *
     * <code>string memory = 4014849 [json_name = "memory", (.buf.validate.field) = { ... }</code>
     * @return The memory.
     */
    public java.lang.String getMemory() {
      java.lang.Object ref = memory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        memory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Memory Capacity of the node defined as MiB, e.g. &#92;"50Mi&#92;"
     * </pre>
     *
     * <code>string memory = 4014849 [json_name = "memory", (.buf.validate.field) = { ... }</code>
     * @return The bytes for memory.
     */
    public com.google.protobuf.ByteString
        getMemoryBytes() {
      java.lang.Object ref = memory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Memory Capacity of the node defined as MiB, e.g. &#92;"50Mi&#92;"
     * </pre>
     *
     * <code>string memory = 4014849 [json_name = "memory", (.buf.validate.field) = { ... }</code>
     * @param value The memory to set.
     * @return This builder for chaining.
     */
    public Builder setMemory(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      memory_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Memory Capacity of the node defined as MiB, e.g. &#92;"50Mi&#92;"
     * </pre>
     *
     * <code>string memory = 4014849 [json_name = "memory", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearMemory() {
      memory_ = getDefaultInstance().getMemory();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Memory Capacity of the node defined as MiB, e.g. &#92;"50Mi&#92;"
     * </pre>
     *
     * <code>string memory = 4014849 [json_name = "memory", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for memory to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      memory_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel> labels_ =
      java.util.Collections.emptyList();
    private void ensureLabelsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        labels_ = new java.util.ArrayList<org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel>(labels_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel, org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel.Builder, org.project_kessel.api.inventory.v1beta1.resources.ResourceLabelOrBuilder> labelsBuilder_;

    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public java.util.List<org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel> getLabelsList() {
      if (labelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(labels_);
      } else {
        return labelsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public int getLabelsCount() {
      if (labelsBuilder_ == null) {
        return labels_.size();
      } else {
        return labelsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel getLabels(int index) {
      if (labelsBuilder_ == null) {
        return labels_.get(index);
      } else {
        return labelsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public Builder setLabels(
        int index, org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.set(index, value);
        onChanged();
      } else {
        labelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public Builder setLabels(
        int index, org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.set(index, builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public Builder addLabels(org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.add(value);
        onChanged();
      } else {
        labelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public Builder addLabels(
        int index, org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel value) {
      if (labelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLabelsIsMutable();
        labels_.add(index, value);
        onChanged();
      } else {
        labelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public Builder addLabels(
        org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.add(builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public Builder addLabels(
        int index, org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel.Builder builderForValue) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.add(index, builderForValue.build());
        onChanged();
      } else {
        labelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public Builder addAllLabels(
        java.lang.Iterable<? extends org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel> values) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, labels_);
        onChanged();
      } else {
        labelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public Builder clearLabels() {
      if (labelsBuilder_ == null) {
        labels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        labelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public Builder removeLabels(int index) {
      if (labelsBuilder_ == null) {
        ensureLabelsIsMutable();
        labels_.remove(index);
        onChanged();
      } else {
        labelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel.Builder getLabelsBuilder(
        int index) {
      return internalGetLabelsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public org.project_kessel.api.inventory.v1beta1.resources.ResourceLabelOrBuilder getLabelsOrBuilder(
        int index) {
      if (labelsBuilder_ == null) {
        return labels_.get(index);  } else {
        return labelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public java.util.List<? extends org.project_kessel.api.inventory.v1beta1.resources.ResourceLabelOrBuilder> 
         getLabelsOrBuilderList() {
      if (labelsBuilder_ != null) {
        return labelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(labels_);
      }
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel.Builder addLabelsBuilder() {
      return internalGetLabelsFieldBuilder().addBuilder(
          org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel.getDefaultInstance());
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel.Builder addLabelsBuilder(
        int index) {
      return internalGetLabelsFieldBuilder().addBuilder(
          index, org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel.getDefaultInstance());
    }
    /**
     * <pre>
     * Map of string keys and string values that can be used to organize and
     * categorize (scope and select) resources
     * Todo: Do we require at least 1 label?
     * </pre>
     *
     * <code>repeated .kessel.inventory.v1beta1.resources.ResourceLabel labels = 36675587 [json_name = "labels", (.buf.validate.field) = { ... }</code>
     */
    public java.util.List<org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel.Builder> 
         getLabelsBuilderList() {
      return internalGetLabelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel, org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel.Builder, org.project_kessel.api.inventory.v1beta1.resources.ResourceLabelOrBuilder> 
        internalGetLabelsFieldBuilder() {
      if (labelsBuilder_ == null) {
        labelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel, org.project_kessel.api.inventory.v1beta1.resources.ResourceLabel.Builder, org.project_kessel.api.inventory.v1beta1.resources.ResourceLabelOrBuilder>(
                labels_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        labels_ = null;
      }
      return labelsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner)
  }

  // @@protoc_insertion_point(class_scope:kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner)
  private static final org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner();
  }

  public static org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<K8sClusterDetailNodesInner>
      PARSER = new com.google.protobuf.AbstractParser<K8sClusterDetailNodesInner>() {
    @java.lang.Override
    public K8sClusterDetailNodesInner parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<K8sClusterDetailNodesInner> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<K8sClusterDetailNodesInner> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

