// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta1/resources/k8s_cluster_detail.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta1.resources;

@com.google.protobuf.Generated
public interface K8sClusterDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta1.resources.K8sClusterDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The OCP cluster ID or ARN etc for *KS
   * </pre>
   *
   * <code>string external_cluster_id = 219571597 [json_name = "external_cluster_id", (.buf.validate.field) = { ... }</code>
   * @return The externalClusterId.
   */
  java.lang.String getExternalClusterId();
  /**
   * <pre>
   * The OCP cluster ID or ARN etc for *KS
   * </pre>
   *
   * <code>string external_cluster_id = 219571597 [json_name = "external_cluster_id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for externalClusterId.
   */
  com.google.protobuf.ByteString
      getExternalClusterIdBytes();

  /**
   * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus cluster_status = 499346904 [json_name = "cluster_status", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for clusterStatus.
   */
  int getClusterStatusValue();
  /**
   * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus cluster_status = 499346904 [json_name = "cluster_status", (.buf.validate.field) = { ... }</code>
   * @return The clusterStatus.
   */
  org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.ClusterStatus getClusterStatus();

  /**
   * <code>optional string cluster_reason = 499346905 [json_name = "cluster_reason", (.buf.validate.field) = { ... }</code>
   * @return Whether the clusterReason field is set.
   */
  boolean hasClusterReason();
  /**
   * <code>optional string cluster_reason = 499346905 [json_name = "cluster_reason", (.buf.validate.field) = { ... }</code>
   * @return The clusterReason.
   */
  java.lang.String getClusterReason();
  /**
   * <code>optional string cluster_reason = 499346905 [json_name = "cluster_reason", (.buf.validate.field) = { ... }</code>
   * @return The bytes for clusterReason.
   */
  com.google.protobuf.ByteString
      getClusterReasonBytes();

  /**
   * <pre>
   * The version of kubernetes
   * </pre>
   *
   * <code>string kube_version = 395858490 [json_name = "kube_version"];</code>
   * @return The kubeVersion.
   */
  java.lang.String getKubeVersion();
  /**
   * <pre>
   * The version of kubernetes
   * </pre>
   *
   * <code>string kube_version = 395858490 [json_name = "kube_version"];</code>
   * @return The bytes for kubeVersion.
   */
  com.google.protobuf.ByteString
      getKubeVersionBytes();

  /**
   * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor kube_vendor = 264191642 [json_name = "kube_vendor", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for kubeVendor.
   */
  int getKubeVendorValue();
  /**
   * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor kube_vendor = 264191642 [json_name = "kube_vendor", (.buf.validate.field) = { ... }</code>
   * @return The kubeVendor.
   */
  org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.KubeVendor getKubeVendor();

  /**
   * <pre>
   * The version of the productized kubernetes distribution
   * </pre>
   *
   * <code>string vendor_version = 23961827 [json_name = "vendor_version", (.buf.validate.field) = { ... }</code>
   * @return The vendorVersion.
   */
  java.lang.String getVendorVersion();
  /**
   * <pre>
   * The version of the productized kubernetes distribution
   * </pre>
   *
   * <code>string vendor_version = 23961827 [json_name = "vendor_version", (.buf.validate.field) = { ... }</code>
   * @return The bytes for vendorVersion.
   */
  com.google.protobuf.ByteString
      getVendorVersionBytes();

  /**
   * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform cloud_platform = 476768062 [json_name = "cloud_platform", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for cloudPlatform.
   */
  int getCloudPlatformValue();
  /**
   * <code>.kessel.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform cloud_platform = 476768062 [json_name = "cloud_platform", (.buf.validate.field) = { ... }</code>
   * @return The cloudPlatform.
   */
  org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetail.CloudPlatform getCloudPlatform();

  /**
   * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
   */
  java.util.List<org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner> 
      getNodesList();
  /**
   * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
   */
  org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInner getNodes(int index);
  /**
   * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
   */
  int getNodesCount();
  /**
   * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
   */
  java.util.List<? extends org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerOrBuilder> 
      getNodesOrBuilderList();
  /**
   * <code>repeated .kessel.inventory.v1beta1.resources.K8sClusterDetailNodesInner nodes = 75440785 [json_name = "nodes"];</code>
   */
  org.project_kessel.api.inventory.v1beta1.resources.K8sClusterDetailNodesInnerOrBuilder getNodesOrBuilder(
      int index);
}
