// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta1/resources/reporter_data.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta1.resources;

/**
 * Protobuf type {@code kessel.inventory.v1beta1.resources.ReporterData}
 */
@com.google.protobuf.Generated
public final class ReporterData extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:kessel.inventory.v1beta1.resources.ReporterData)
    ReporterDataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      ReporterData.class.getName());
  }
  // Use ReporterData.newBuilder() to construct.
  private ReporterData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ReporterData() {
    reporterType_ = 0;
    reporterInstanceId_ = "";
    consoleHref_ = "";
    apiHref_ = "";
    localResourceId_ = "";
    reporterVersion_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.project_kessel.api.inventory.v1beta1.resources.ReporterDataOuterClass.internal_static_kessel_inventory_v1beta1_resources_ReporterData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.project_kessel.api.inventory.v1beta1.resources.ReporterDataOuterClass.internal_static_kessel_inventory_v1beta1_resources_ReporterData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.project_kessel.api.inventory.v1beta1.resources.ReporterData.class, org.project_kessel.api.inventory.v1beta1.resources.ReporterData.Builder.class);
  }

  /**
   * Protobuf enum {@code kessel.inventory.v1beta1.resources.ReporterData.ReporterType}
   */
  public enum ReporterType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REPORTER_TYPE_UNSPECIFIED = 0;</code>
     */
    REPORTER_TYPE_UNSPECIFIED(0),
    /**
     * <code>REPORTER_TYPE_OTHER = 1;</code>
     */
    REPORTER_TYPE_OTHER(1),
    /**
     * <code>ACM = 2;</code>
     */
    ACM(2),
    /**
     * <code>HBI = 3;</code>
     */
    HBI(3),
    /**
     * <code>OCM = 4;</code>
     */
    OCM(4),
    /**
     * <code>NOTIFICATIONS = 5;</code>
     */
    NOTIFICATIONS(5),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        ReporterType.class.getName());
    }
    /**
     * <code>REPORTER_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int REPORTER_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>REPORTER_TYPE_OTHER = 1;</code>
     */
    public static final int REPORTER_TYPE_OTHER_VALUE = 1;
    /**
     * <code>ACM = 2;</code>
     */
    public static final int ACM_VALUE = 2;
    /**
     * <code>HBI = 3;</code>
     */
    public static final int HBI_VALUE = 3;
    /**
     * <code>OCM = 4;</code>
     */
    public static final int OCM_VALUE = 4;
    /**
     * <code>NOTIFICATIONS = 5;</code>
     */
    public static final int NOTIFICATIONS_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ReporterType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ReporterType forNumber(int value) {
      switch (value) {
        case 0: return REPORTER_TYPE_UNSPECIFIED;
        case 1: return REPORTER_TYPE_OTHER;
        case 2: return ACM;
        case 3: return HBI;
        case 4: return OCM;
        case 5: return NOTIFICATIONS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ReporterType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ReporterType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReporterType>() {
            public ReporterType findValueByNumber(int number) {
              return ReporterType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta1.resources.ReporterData.getDescriptor().getEnumTypes().get(0);
    }

    private static final ReporterType[] VALUES = values();

    public static ReporterType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ReporterType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:kessel.inventory.v1beta1.resources.ReporterData.ReporterType)
  }

  public static final int REPORTER_TYPE_FIELD_NUMBER = 245778392;
  private int reporterType_ = 0;
  /**
   * <code>.kessel.inventory.v1beta1.resources.ReporterData.ReporterType reporter_type = 245778392 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for reporterType.
   */
  @java.lang.Override public int getReporterTypeValue() {
    return reporterType_;
  }
  /**
   * <code>.kessel.inventory.v1beta1.resources.ReporterData.ReporterType reporter_type = 245778392 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
   * @return The reporterType.
   */
  @java.lang.Override public org.project_kessel.api.inventory.v1beta1.resources.ReporterData.ReporterType getReporterType() {
    org.project_kessel.api.inventory.v1beta1.resources.ReporterData.ReporterType result = org.project_kessel.api.inventory.v1beta1.resources.ReporterData.ReporterType.forNumber(reporterType_);
    return result == null ? org.project_kessel.api.inventory.v1beta1.resources.ReporterData.ReporterType.UNRECOGNIZED : result;
  }

  public static final int REPORTER_INSTANCE_ID_FIELD_NUMBER = 241085112;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reporterInstanceId_ = "";
  /**
   * <pre>
   * The ID of the instance of the reporter. This is derived from the
   * authentication mechanism, i.e. authentication token.
   * </pre>
   *
   * <code>string reporter_instance_id = 241085112 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The reporterInstanceId.
   */
  @java.lang.Override
  public java.lang.String getReporterInstanceId() {
    java.lang.Object ref = reporterInstanceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reporterInstanceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID of the instance of the reporter. This is derived from the
   * authentication mechanism, i.e. authentication token.
   * </pre>
   *
   * <code>string reporter_instance_id = 241085112 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The bytes for reporterInstanceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReporterInstanceIdBytes() {
    java.lang.Object ref = reporterInstanceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reporterInstanceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONSOLE_HREF_FIELD_NUMBER = 145854740;
  @SuppressWarnings("serial")
  private volatile java.lang.Object consoleHref_ = "";
  /**
   * <pre>
   * The URL for this resource in the reporter's management UI console. For
   * example this would be the cluster URL in the HCC Console for an OCM
   * reported cluster.
   * </pre>
   *
   * <code>string console_href = 145854740 [json_name = "console_href"];</code>
   * @return The consoleHref.
   */
  @java.lang.Override
  public java.lang.String getConsoleHref() {
    java.lang.Object ref = consoleHref_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      consoleHref_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The URL for this resource in the reporter's management UI console. For
   * example this would be the cluster URL in the HCC Console for an OCM
   * reported cluster.
   * </pre>
   *
   * <code>string console_href = 145854740 [json_name = "console_href"];</code>
   * @return The bytes for consoleHref.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConsoleHrefBytes() {
    java.lang.Object ref = consoleHref_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      consoleHref_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int API_HREF_FIELD_NUMBER = 430210609;
  @SuppressWarnings("serial")
  private volatile java.lang.Object apiHref_ = "";
  /**
   * <pre>
   * Reporter specific API link to the resource.
   * </pre>
   *
   * <code>string api_href = 430210609 [json_name = "api_href"];</code>
   * @return The apiHref.
   */
  @java.lang.Override
  public java.lang.String getApiHref() {
    java.lang.Object ref = apiHref_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      apiHref_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Reporter specific API link to the resource.
   * </pre>
   *
   * <code>string api_href = 430210609 [json_name = "api_href"];</code>
   * @return The bytes for apiHref.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getApiHrefBytes() {
    java.lang.Object ref = apiHref_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      apiHref_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCAL_RESOURCE_ID_FIELD_NUMBER = 508976189;
  @SuppressWarnings("serial")
  private volatile java.lang.Object localResourceId_ = "";
  /**
   * <pre>
   * The ID assigned to this resource by the reporter, for example OCM cluster
   * ID, HBI's host id, or ACM managed cluster name etc.
   * </pre>
   *
   * <code>string local_resource_id = 508976189 [json_name = "local_resource_id", (.buf.validate.field) = { ... }</code>
   * @return The localResourceId.
   */
  @java.lang.Override
  public java.lang.String getLocalResourceId() {
    java.lang.Object ref = localResourceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      localResourceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID assigned to this resource by the reporter, for example OCM cluster
   * ID, HBI's host id, or ACM managed cluster name etc.
   * </pre>
   *
   * <code>string local_resource_id = 508976189 [json_name = "local_resource_id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for localResourceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocalResourceIdBytes() {
    java.lang.Object ref = localResourceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      localResourceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPORTER_VERSION_FIELD_NUMBER = 269629306;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reporterVersion_ = "";
  /**
   * <pre>
   * version of the reporter
   * </pre>
   *
   * <code>string reporter_version = 269629306 [json_name = "reporter_version"];</code>
   * @return The reporterVersion.
   */
  @java.lang.Override
  public java.lang.String getReporterVersion() {
    java.lang.Object ref = reporterVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reporterVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * version of the reporter
   * </pre>
   *
   * <code>string reporter_version = 269629306 [json_name = "reporter_version"];</code>
   * @return The bytes for reporterVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReporterVersionBytes() {
    java.lang.Object ref = reporterVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reporterVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(consoleHref_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 145854740, consoleHref_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reporterInstanceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 241085112, reporterInstanceId_);
    }
    if (reporterType_ != org.project_kessel.api.inventory.v1beta1.resources.ReporterData.ReporterType.REPORTER_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(245778392, reporterType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reporterVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 269629306, reporterVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(apiHref_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 430210609, apiHref_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(localResourceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 508976189, localResourceId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(consoleHref_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(145854740, consoleHref_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reporterInstanceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(241085112, reporterInstanceId_);
    }
    if (reporterType_ != org.project_kessel.api.inventory.v1beta1.resources.ReporterData.ReporterType.REPORTER_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(245778392, reporterType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reporterVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(269629306, reporterVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(apiHref_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(430210609, apiHref_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(localResourceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(508976189, localResourceId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.project_kessel.api.inventory.v1beta1.resources.ReporterData)) {
      return super.equals(obj);
    }
    org.project_kessel.api.inventory.v1beta1.resources.ReporterData other = (org.project_kessel.api.inventory.v1beta1.resources.ReporterData) obj;

    if (reporterType_ != other.reporterType_) return false;
    if (!getReporterInstanceId()
        .equals(other.getReporterInstanceId())) return false;
    if (!getConsoleHref()
        .equals(other.getConsoleHref())) return false;
    if (!getApiHref()
        .equals(other.getApiHref())) return false;
    if (!getLocalResourceId()
        .equals(other.getLocalResourceId())) return false;
    if (!getReporterVersion()
        .equals(other.getReporterVersion())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REPORTER_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + reporterType_;
    hash = (37 * hash) + REPORTER_INSTANCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReporterInstanceId().hashCode();
    hash = (37 * hash) + CONSOLE_HREF_FIELD_NUMBER;
    hash = (53 * hash) + getConsoleHref().hashCode();
    hash = (37 * hash) + API_HREF_FIELD_NUMBER;
    hash = (53 * hash) + getApiHref().hashCode();
    hash = (37 * hash) + LOCAL_RESOURCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getLocalResourceId().hashCode();
    hash = (37 * hash) + REPORTER_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getReporterVersion().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.project_kessel.api.inventory.v1beta1.resources.ReporterData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.ReporterData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.ReporterData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.ReporterData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.ReporterData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.ReporterData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.ReporterData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.ReporterData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.project_kessel.api.inventory.v1beta1.resources.ReporterData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.project_kessel.api.inventory.v1beta1.resources.ReporterData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.ReporterData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta1.resources.ReporterData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.project_kessel.api.inventory.v1beta1.resources.ReporterData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kessel.inventory.v1beta1.resources.ReporterData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kessel.inventory.v1beta1.resources.ReporterData)
      org.project_kessel.api.inventory.v1beta1.resources.ReporterDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta1.resources.ReporterDataOuterClass.internal_static_kessel_inventory_v1beta1_resources_ReporterData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.project_kessel.api.inventory.v1beta1.resources.ReporterDataOuterClass.internal_static_kessel_inventory_v1beta1_resources_ReporterData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project_kessel.api.inventory.v1beta1.resources.ReporterData.class, org.project_kessel.api.inventory.v1beta1.resources.ReporterData.Builder.class);
    }

    // Construct using org.project_kessel.api.inventory.v1beta1.resources.ReporterData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      reporterType_ = 0;
      reporterInstanceId_ = "";
      consoleHref_ = "";
      apiHref_ = "";
      localResourceId_ = "";
      reporterVersion_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.project_kessel.api.inventory.v1beta1.resources.ReporterDataOuterClass.internal_static_kessel_inventory_v1beta1_resources_ReporterData_descriptor;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.resources.ReporterData getDefaultInstanceForType() {
      return org.project_kessel.api.inventory.v1beta1.resources.ReporterData.getDefaultInstance();
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.resources.ReporterData build() {
      org.project_kessel.api.inventory.v1beta1.resources.ReporterData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.resources.ReporterData buildPartial() {
      org.project_kessel.api.inventory.v1beta1.resources.ReporterData result = new org.project_kessel.api.inventory.v1beta1.resources.ReporterData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.project_kessel.api.inventory.v1beta1.resources.ReporterData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.reporterType_ = reporterType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.reporterInstanceId_ = reporterInstanceId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.consoleHref_ = consoleHref_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.apiHref_ = apiHref_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.localResourceId_ = localResourceId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.reporterVersion_ = reporterVersion_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.project_kessel.api.inventory.v1beta1.resources.ReporterData) {
        return mergeFrom((org.project_kessel.api.inventory.v1beta1.resources.ReporterData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.project_kessel.api.inventory.v1beta1.resources.ReporterData other) {
      if (other == org.project_kessel.api.inventory.v1beta1.resources.ReporterData.getDefaultInstance()) return this;
      if (other.reporterType_ != 0) {
        setReporterTypeValue(other.getReporterTypeValue());
      }
      if (!other.getReporterInstanceId().isEmpty()) {
        reporterInstanceId_ = other.reporterInstanceId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getConsoleHref().isEmpty()) {
        consoleHref_ = other.consoleHref_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getApiHref().isEmpty()) {
        apiHref_ = other.apiHref_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getLocalResourceId().isEmpty()) {
        localResourceId_ = other.localResourceId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getReporterVersion().isEmpty()) {
        reporterVersion_ = other.reporterVersion_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 1166837922: {
              consoleHref_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 1166837922
            case 1928680898: {
              reporterInstanceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 1928680898
            case 1966227136: {
              reporterType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 1966227136
            case -2137932846: {
              reporterVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case -2137932846
            case -853282422: {
              apiHref_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case -853282422
            case -223157782: {
              localResourceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case -223157782
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int reporterType_ = 0;
    /**
     * <code>.kessel.inventory.v1beta1.resources.ReporterData.ReporterType reporter_type = 245778392 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
     * @return The enum numeric value on the wire for reporterType.
     */
    @java.lang.Override public int getReporterTypeValue() {
      return reporterType_;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.ReporterData.ReporterType reporter_type = 245778392 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
     * @param value The enum numeric value on the wire for reporterType to set.
     * @return This builder for chaining.
     */
    public Builder setReporterTypeValue(int value) {
      reporterType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.ReporterData.ReporterType reporter_type = 245778392 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
     * @return The reporterType.
     */
    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.resources.ReporterData.ReporterType getReporterType() {
      org.project_kessel.api.inventory.v1beta1.resources.ReporterData.ReporterType result = org.project_kessel.api.inventory.v1beta1.resources.ReporterData.ReporterType.forNumber(reporterType_);
      return result == null ? org.project_kessel.api.inventory.v1beta1.resources.ReporterData.ReporterType.UNRECOGNIZED : result;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.ReporterData.ReporterType reporter_type = 245778392 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
     * @param value The reporterType to set.
     * @return This builder for chaining.
     */
    public Builder setReporterType(org.project_kessel.api.inventory.v1beta1.resources.ReporterData.ReporterType value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      reporterType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta1.resources.ReporterData.ReporterType reporter_type = 245778392 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearReporterType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      reporterType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object reporterInstanceId_ = "";
    /**
     * <pre>
     * The ID of the instance of the reporter. This is derived from the
     * authentication mechanism, i.e. authentication token.
     * </pre>
     *
     * <code>string reporter_instance_id = 241085112 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return The reporterInstanceId.
     */
    public java.lang.String getReporterInstanceId() {
      java.lang.Object ref = reporterInstanceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reporterInstanceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID of the instance of the reporter. This is derived from the
     * authentication mechanism, i.e. authentication token.
     * </pre>
     *
     * <code>string reporter_instance_id = 241085112 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return The bytes for reporterInstanceId.
     */
    public com.google.protobuf.ByteString
        getReporterInstanceIdBytes() {
      java.lang.Object ref = reporterInstanceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reporterInstanceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID of the instance of the reporter. This is derived from the
     * authentication mechanism, i.e. authentication token.
     * </pre>
     *
     * <code>string reporter_instance_id = 241085112 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param value The reporterInstanceId to set.
     * @return This builder for chaining.
     */
    public Builder setReporterInstanceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reporterInstanceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the instance of the reporter. This is derived from the
     * authentication mechanism, i.e. authentication token.
     * </pre>
     *
     * <code>string reporter_instance_id = 241085112 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return This builder for chaining.
     */
    public Builder clearReporterInstanceId() {
      reporterInstanceId_ = getDefaultInstance().getReporterInstanceId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the instance of the reporter. This is derived from the
     * authentication mechanism, i.e. authentication token.
     * </pre>
     *
     * <code>string reporter_instance_id = 241085112 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param value The bytes for reporterInstanceId to set.
     * @return This builder for chaining.
     */
    public Builder setReporterInstanceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reporterInstanceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object consoleHref_ = "";
    /**
     * <pre>
     * The URL for this resource in the reporter's management UI console. For
     * example this would be the cluster URL in the HCC Console for an OCM
     * reported cluster.
     * </pre>
     *
     * <code>string console_href = 145854740 [json_name = "console_href"];</code>
     * @return The consoleHref.
     */
    public java.lang.String getConsoleHref() {
      java.lang.Object ref = consoleHref_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        consoleHref_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The URL for this resource in the reporter's management UI console. For
     * example this would be the cluster URL in the HCC Console for an OCM
     * reported cluster.
     * </pre>
     *
     * <code>string console_href = 145854740 [json_name = "console_href"];</code>
     * @return The bytes for consoleHref.
     */
    public com.google.protobuf.ByteString
        getConsoleHrefBytes() {
      java.lang.Object ref = consoleHref_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consoleHref_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The URL for this resource in the reporter's management UI console. For
     * example this would be the cluster URL in the HCC Console for an OCM
     * reported cluster.
     * </pre>
     *
     * <code>string console_href = 145854740 [json_name = "console_href"];</code>
     * @param value The consoleHref to set.
     * @return This builder for chaining.
     */
    public Builder setConsoleHref(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      consoleHref_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The URL for this resource in the reporter's management UI console. For
     * example this would be the cluster URL in the HCC Console for an OCM
     * reported cluster.
     * </pre>
     *
     * <code>string console_href = 145854740 [json_name = "console_href"];</code>
     * @return This builder for chaining.
     */
    public Builder clearConsoleHref() {
      consoleHref_ = getDefaultInstance().getConsoleHref();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The URL for this resource in the reporter's management UI console. For
     * example this would be the cluster URL in the HCC Console for an OCM
     * reported cluster.
     * </pre>
     *
     * <code>string console_href = 145854740 [json_name = "console_href"];</code>
     * @param value The bytes for consoleHref to set.
     * @return This builder for chaining.
     */
    public Builder setConsoleHrefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      consoleHref_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object apiHref_ = "";
    /**
     * <pre>
     * Reporter specific API link to the resource.
     * </pre>
     *
     * <code>string api_href = 430210609 [json_name = "api_href"];</code>
     * @return The apiHref.
     */
    public java.lang.String getApiHref() {
      java.lang.Object ref = apiHref_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apiHref_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Reporter specific API link to the resource.
     * </pre>
     *
     * <code>string api_href = 430210609 [json_name = "api_href"];</code>
     * @return The bytes for apiHref.
     */
    public com.google.protobuf.ByteString
        getApiHrefBytes() {
      java.lang.Object ref = apiHref_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apiHref_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Reporter specific API link to the resource.
     * </pre>
     *
     * <code>string api_href = 430210609 [json_name = "api_href"];</code>
     * @param value The apiHref to set.
     * @return This builder for chaining.
     */
    public Builder setApiHref(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      apiHref_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Reporter specific API link to the resource.
     * </pre>
     *
     * <code>string api_href = 430210609 [json_name = "api_href"];</code>
     * @return This builder for chaining.
     */
    public Builder clearApiHref() {
      apiHref_ = getDefaultInstance().getApiHref();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Reporter specific API link to the resource.
     * </pre>
     *
     * <code>string api_href = 430210609 [json_name = "api_href"];</code>
     * @param value The bytes for apiHref to set.
     * @return This builder for chaining.
     */
    public Builder setApiHrefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      apiHref_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object localResourceId_ = "";
    /**
     * <pre>
     * The ID assigned to this resource by the reporter, for example OCM cluster
     * ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string local_resource_id = 508976189 [json_name = "local_resource_id", (.buf.validate.field) = { ... }</code>
     * @return The localResourceId.
     */
    public java.lang.String getLocalResourceId() {
      java.lang.Object ref = localResourceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        localResourceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID assigned to this resource by the reporter, for example OCM cluster
     * ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string local_resource_id = 508976189 [json_name = "local_resource_id", (.buf.validate.field) = { ... }</code>
     * @return The bytes for localResourceId.
     */
    public com.google.protobuf.ByteString
        getLocalResourceIdBytes() {
      java.lang.Object ref = localResourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localResourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID assigned to this resource by the reporter, for example OCM cluster
     * ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string local_resource_id = 508976189 [json_name = "local_resource_id", (.buf.validate.field) = { ... }</code>
     * @param value The localResourceId to set.
     * @return This builder for chaining.
     */
    public Builder setLocalResourceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      localResourceId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID assigned to this resource by the reporter, for example OCM cluster
     * ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string local_resource_id = 508976189 [json_name = "local_resource_id", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearLocalResourceId() {
      localResourceId_ = getDefaultInstance().getLocalResourceId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID assigned to this resource by the reporter, for example OCM cluster
     * ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string local_resource_id = 508976189 [json_name = "local_resource_id", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for localResourceId to set.
     * @return This builder for chaining.
     */
    public Builder setLocalResourceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      localResourceId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object reporterVersion_ = "";
    /**
     * <pre>
     * version of the reporter
     * </pre>
     *
     * <code>string reporter_version = 269629306 [json_name = "reporter_version"];</code>
     * @return The reporterVersion.
     */
    public java.lang.String getReporterVersion() {
      java.lang.Object ref = reporterVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reporterVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * version of the reporter
     * </pre>
     *
     * <code>string reporter_version = 269629306 [json_name = "reporter_version"];</code>
     * @return The bytes for reporterVersion.
     */
    public com.google.protobuf.ByteString
        getReporterVersionBytes() {
      java.lang.Object ref = reporterVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reporterVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * version of the reporter
     * </pre>
     *
     * <code>string reporter_version = 269629306 [json_name = "reporter_version"];</code>
     * @param value The reporterVersion to set.
     * @return This builder for chaining.
     */
    public Builder setReporterVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reporterVersion_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * version of the reporter
     * </pre>
     *
     * <code>string reporter_version = 269629306 [json_name = "reporter_version"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReporterVersion() {
      reporterVersion_ = getDefaultInstance().getReporterVersion();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * version of the reporter
     * </pre>
     *
     * <code>string reporter_version = 269629306 [json_name = "reporter_version"];</code>
     * @param value The bytes for reporterVersion to set.
     * @return This builder for chaining.
     */
    public Builder setReporterVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reporterVersion_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:kessel.inventory.v1beta1.resources.ReporterData)
  }

  // @@protoc_insertion_point(class_scope:kessel.inventory.v1beta1.resources.ReporterData)
  private static final org.project_kessel.api.inventory.v1beta1.resources.ReporterData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.project_kessel.api.inventory.v1beta1.resources.ReporterData();
  }

  public static org.project_kessel.api.inventory.v1beta1.resources.ReporterData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReporterData>
      PARSER = new com.google.protobuf.AbstractParser<ReporterData>() {
    @java.lang.Override
    public ReporterData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReporterData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReporterData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta1.resources.ReporterData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

