// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta1/authz/check.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta1.authz;

@com.google.protobuf.Generated
public interface CheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta1.authz.CheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required parameters (from an authz perspective)
   * - resource type and id
   * - permission (cannot be derived from the type as a type may have multiple 'read' permissions. Ex: https://github.com/RedHatInsights/rbac-config/blob/master/configs/prod/schemas/src/notifications.ksl#L31)
   * - user (possibly derived from an identity token)
   * </pre>
   *
   * <code>.kessel.inventory.v1beta1.authz.ObjectReference parent = 1 [json_name = "parent", (.buf.validate.field) = { ... }</code>
   * @return Whether the parent field is set.
   */
  boolean hasParent();
  /**
   * <pre>
   * Required parameters (from an authz perspective)
   * - resource type and id
   * - permission (cannot be derived from the type as a type may have multiple 'read' permissions. Ex: https://github.com/RedHatInsights/rbac-config/blob/master/configs/prod/schemas/src/notifications.ksl#L31)
   * - user (possibly derived from an identity token)
   * </pre>
   *
   * <code>.kessel.inventory.v1beta1.authz.ObjectReference parent = 1 [json_name = "parent", (.buf.validate.field) = { ... }</code>
   * @return The parent.
   */
  org.project_kessel.api.inventory.v1beta1.authz.ObjectReference getParent();
  /**
   * <pre>
   * Required parameters (from an authz perspective)
   * - resource type and id
   * - permission (cannot be derived from the type as a type may have multiple 'read' permissions. Ex: https://github.com/RedHatInsights/rbac-config/blob/master/configs/prod/schemas/src/notifications.ksl#L31)
   * - user (possibly derived from an identity token)
   * </pre>
   *
   * <code>.kessel.inventory.v1beta1.authz.ObjectReference parent = 1 [json_name = "parent", (.buf.validate.field) = { ... }</code>
   */
  org.project_kessel.api.inventory.v1beta1.authz.ObjectReferenceOrBuilder getParentOrBuilder();

  /**
   * <code>string relation = 2 [json_name = "relation", (.buf.validate.field) = { ... }</code>
   * @return The relation.
   */
  java.lang.String getRelation();
  /**
   * <code>string relation = 2 [json_name = "relation", (.buf.validate.field) = { ... }</code>
   * @return The bytes for relation.
   */
  com.google.protobuf.ByteString
      getRelationBytes();

  /**
   * <pre>
   * Consistency consistency = 4;
   * </pre>
   *
   * <code>.kessel.inventory.v1beta1.authz.SubjectReference subject = 3 [json_name = "subject", (.buf.validate.field) = { ... }</code>
   * @return Whether the subject field is set.
   */
  boolean hasSubject();
  /**
   * <pre>
   * Consistency consistency = 4;
   * </pre>
   *
   * <code>.kessel.inventory.v1beta1.authz.SubjectReference subject = 3 [json_name = "subject", (.buf.validate.field) = { ... }</code>
   * @return The subject.
   */
  org.project_kessel.api.inventory.v1beta1.authz.SubjectReference getSubject();
  /**
   * <pre>
   * Consistency consistency = 4;
   * </pre>
   *
   * <code>.kessel.inventory.v1beta1.authz.SubjectReference subject = 3 [json_name = "subject", (.buf.validate.field) = { ... }</code>
   */
  org.project_kessel.api.inventory.v1beta1.authz.SubjectReferenceOrBuilder getSubjectOrBuilder();
}
