// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta1/authz/common.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta1.authz;

@com.google.protobuf.Generated
public interface RelationshipOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta1.authz.Relationship)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kessel.inventory.v1beta1.authz.ObjectReference resource = 1 [json_name = "resource", (.buf.validate.field) = { ... }</code>
   * @return Whether the resource field is set.
   */
  boolean hasResource();
  /**
   * <code>.kessel.inventory.v1beta1.authz.ObjectReference resource = 1 [json_name = "resource", (.buf.validate.field) = { ... }</code>
   * @return The resource.
   */
  org.project_kessel.api.inventory.v1beta1.authz.ObjectReference getResource();
  /**
   * <code>.kessel.inventory.v1beta1.authz.ObjectReference resource = 1 [json_name = "resource", (.buf.validate.field) = { ... }</code>
   */
  org.project_kessel.api.inventory.v1beta1.authz.ObjectReferenceOrBuilder getResourceOrBuilder();

  /**
   * <code>string relation = 2 [json_name = "relation", (.buf.validate.field) = { ... }</code>
   * @return The relation.
   */
  java.lang.String getRelation();
  /**
   * <code>string relation = 2 [json_name = "relation", (.buf.validate.field) = { ... }</code>
   * @return The bytes for relation.
   */
  com.google.protobuf.ByteString
      getRelationBytes();

  /**
   * <code>.kessel.inventory.v1beta1.authz.SubjectReference subject = 3 [json_name = "subject", (.buf.validate.field) = { ... }</code>
   * @return Whether the subject field is set.
   */
  boolean hasSubject();
  /**
   * <code>.kessel.inventory.v1beta1.authz.SubjectReference subject = 3 [json_name = "subject", (.buf.validate.field) = { ... }</code>
   * @return The subject.
   */
  org.project_kessel.api.inventory.v1beta1.authz.SubjectReference getSubject();
  /**
   * <code>.kessel.inventory.v1beta1.authz.SubjectReference subject = 3 [json_name = "subject", (.buf.validate.field) = { ... }</code>
   */
  org.project_kessel.api.inventory.v1beta1.authz.SubjectReferenceOrBuilder getSubjectOrBuilder();
}
