// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster_service.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta1.relationships;

@com.google.protobuf.Generated
public interface DeleteK8SPolicyIsPropagatedToK8SClusterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta1.relationships.DeleteK8SPolicyIsPropagatedToK8SClusterResponse)
    com.google.protobuf.MessageOrBuilder {
}
