// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster_detail.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta1.relationships;

/**
 * Protobuf type {@code kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail}
 */
@com.google.protobuf.Generated
public final class K8SPolicyIsPropagatedToK8SClusterDetail extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail)
    K8SPolicyIsPropagatedToK8SClusterDetailOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      K8SPolicyIsPropagatedToK8SClusterDetail.class.getName());
  }
  // Use K8SPolicyIsPropagatedToK8SClusterDetail.newBuilder() to construct.
  private K8SPolicyIsPropagatedToK8SClusterDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private K8SPolicyIsPropagatedToK8SClusterDetail() {
    k8SPolicyId_ = "";
    k8SClusterId_ = "";
    status_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetailProto.internal_static_kessel_inventory_v1beta1_relationships_K8SPolicyIsPropagatedToK8SClusterDetail_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetailProto.internal_static_kessel_inventory_v1beta1_relationships_K8SPolicyIsPropagatedToK8SClusterDetail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.class, org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Builder.class);
  }

  /**
   * <pre>
   * the aggregate status of the cluster
   * </pre>
   *
   * Protobuf enum {@code kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATUS_UNSPECIFIED = 0;</code>
     */
    STATUS_UNSPECIFIED(0),
    /**
     * <code>STATUS_OTHER = 1;</code>
     */
    STATUS_OTHER(1),
    /**
     * <code>VIOLATIONS = 2;</code>
     */
    VIOLATIONS(2),
    /**
     * <code>NO_VIOLATIONS = 3;</code>
     */
    NO_VIOLATIONS(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        Status.class.getName());
    }
    /**
     * <code>STATUS_UNSPECIFIED = 0;</code>
     */
    public static final int STATUS_UNSPECIFIED_VALUE = 0;
    /**
     * <code>STATUS_OTHER = 1;</code>
     */
    public static final int STATUS_OTHER_VALUE = 1;
    /**
     * <code>VIOLATIONS = 2;</code>
     */
    public static final int VIOLATIONS_VALUE = 2;
    /**
     * <code>NO_VIOLATIONS = 3;</code>
     */
    public static final int NO_VIOLATIONS_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Status forNumber(int value) {
      switch (value) {
        case 0: return STATUS_UNSPECIFIED;
        case 1: return STATUS_OTHER;
        case 2: return VIOLATIONS;
        case 3: return NO_VIOLATIONS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status)
  }

  public static final int K8S_POLICY_ID_FIELD_NUMBER = 225679544;
  @SuppressWarnings("serial")
  private volatile java.lang.Object k8SPolicyId_ = "";
  /**
   * <pre>
   * The resource ID assigned to the resource by Kessel Asset Inventory. 
   * </pre>
   *
   * <code>string k8s_policy_id = 225679544 [json_name = "k8s_policy_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The k8sPolicyId.
   */
  @java.lang.Override
  public java.lang.String getK8SPolicyId() {
    java.lang.Object ref = k8SPolicyId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      k8SPolicyId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The resource ID assigned to the resource by Kessel Asset Inventory. 
   * </pre>
   *
   * <code>string k8s_policy_id = 225679544 [json_name = "k8s_policy_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The bytes for k8sPolicyId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getK8SPolicyIdBytes() {
    java.lang.Object ref = k8SPolicyId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      k8SPolicyId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int K8S_CLUSTER_ID_FIELD_NUMBER = 240280960;
  @SuppressWarnings("serial")
  private volatile java.lang.Object k8SClusterId_ = "";
  /**
   * <pre>
   * The resource ID assigned to the resource by Kessel Asset Inventory. 
   * </pre>
   *
   * <code>string k8s_cluster_id = 240280960 [json_name = "k8s_cluster_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The k8sClusterId.
   */
  @java.lang.Override
  public java.lang.String getK8SClusterId() {
    java.lang.Object ref = k8SClusterId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      k8SClusterId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The resource ID assigned to the resource by Kessel Asset Inventory. 
   * </pre>
   *
   * <code>string k8s_cluster_id = 240280960 [json_name = "k8s_cluster_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The bytes for k8sClusterId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getK8SClusterIdBytes() {
    java.lang.Object ref = k8SClusterId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      k8SClusterId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 355610639;
  private int status_ = 0;
  /**
   * <code>.kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status status = 355610639 [json_name = "status", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status status = 355610639 [json_name = "status", (.buf.validate.field) = { ... }</code>
   * @return The status.
   */
  @java.lang.Override public org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status getStatus() {
    org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status result = org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status.forNumber(status_);
    return result == null ? org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(k8SPolicyId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 225679544, k8SPolicyId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(k8SClusterId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 240280960, k8SClusterId_);
    }
    if (status_ != org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status.STATUS_UNSPECIFIED.getNumber()) {
      output.writeEnum(355610639, status_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(k8SPolicyId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(225679544, k8SPolicyId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(k8SClusterId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(240280960, k8SClusterId_);
    }
    if (status_ != org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status.STATUS_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(355610639, status_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail)) {
      return super.equals(obj);
    }
    org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail other = (org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail) obj;

    if (!getK8SPolicyId()
        .equals(other.getK8SPolicyId())) return false;
    if (!getK8SClusterId()
        .equals(other.getK8SClusterId())) return false;
    if (status_ != other.status_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + K8S_POLICY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getK8SPolicyId().hashCode();
    hash = (37 * hash) + K8S_CLUSTER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getK8SClusterId().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail)
      org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetailProto.internal_static_kessel_inventory_v1beta1_relationships_K8SPolicyIsPropagatedToK8SClusterDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetailProto.internal_static_kessel_inventory_v1beta1_relationships_K8SPolicyIsPropagatedToK8SClusterDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.class, org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Builder.class);
    }

    // Construct using org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      k8SPolicyId_ = "";
      k8SClusterId_ = "";
      status_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetailProto.internal_static_kessel_inventory_v1beta1_relationships_K8SPolicyIsPropagatedToK8SClusterDetail_descriptor;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail getDefaultInstanceForType() {
      return org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.getDefaultInstance();
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail build() {
      org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail buildPartial() {
      org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail result = new org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.k8SPolicyId_ = k8SPolicyId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.k8SClusterId_ = k8SClusterId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.status_ = status_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail) {
        return mergeFrom((org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail other) {
      if (other == org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.getDefaultInstance()) return this;
      if (!other.getK8SPolicyId().isEmpty()) {
        k8SPolicyId_ = other.k8SPolicyId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getK8SClusterId().isEmpty()) {
        k8SClusterId_ = other.k8SClusterId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 1805436354: {
              k8SPolicyId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 1805436354
            case 1922247682: {
              k8SClusterId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 1922247682
            case -1450082184: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case -1450082184
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object k8SPolicyId_ = "";
    /**
     * <pre>
     * The resource ID assigned to the resource by Kessel Asset Inventory. 
     * </pre>
     *
     * <code>string k8s_policy_id = 225679544 [json_name = "k8s_policy_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return The k8sPolicyId.
     */
    public java.lang.String getK8SPolicyId() {
      java.lang.Object ref = k8SPolicyId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        k8SPolicyId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The resource ID assigned to the resource by Kessel Asset Inventory. 
     * </pre>
     *
     * <code>string k8s_policy_id = 225679544 [json_name = "k8s_policy_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return The bytes for k8sPolicyId.
     */
    public com.google.protobuf.ByteString
        getK8SPolicyIdBytes() {
      java.lang.Object ref = k8SPolicyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        k8SPolicyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The resource ID assigned to the resource by Kessel Asset Inventory. 
     * </pre>
     *
     * <code>string k8s_policy_id = 225679544 [json_name = "k8s_policy_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param value The k8sPolicyId to set.
     * @return This builder for chaining.
     */
    public Builder setK8SPolicyId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      k8SPolicyId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The resource ID assigned to the resource by Kessel Asset Inventory. 
     * </pre>
     *
     * <code>string k8s_policy_id = 225679544 [json_name = "k8s_policy_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return This builder for chaining.
     */
    public Builder clearK8SPolicyId() {
      k8SPolicyId_ = getDefaultInstance().getK8SPolicyId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The resource ID assigned to the resource by Kessel Asset Inventory. 
     * </pre>
     *
     * <code>string k8s_policy_id = 225679544 [json_name = "k8s_policy_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param value The bytes for k8sPolicyId to set.
     * @return This builder for chaining.
     */
    public Builder setK8SPolicyIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      k8SPolicyId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object k8SClusterId_ = "";
    /**
     * <pre>
     * The resource ID assigned to the resource by Kessel Asset Inventory. 
     * </pre>
     *
     * <code>string k8s_cluster_id = 240280960 [json_name = "k8s_cluster_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return The k8sClusterId.
     */
    public java.lang.String getK8SClusterId() {
      java.lang.Object ref = k8SClusterId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        k8SClusterId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The resource ID assigned to the resource by Kessel Asset Inventory. 
     * </pre>
     *
     * <code>string k8s_cluster_id = 240280960 [json_name = "k8s_cluster_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return The bytes for k8sClusterId.
     */
    public com.google.protobuf.ByteString
        getK8SClusterIdBytes() {
      java.lang.Object ref = k8SClusterId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        k8SClusterId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The resource ID assigned to the resource by Kessel Asset Inventory. 
     * </pre>
     *
     * <code>string k8s_cluster_id = 240280960 [json_name = "k8s_cluster_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param value The k8sClusterId to set.
     * @return This builder for chaining.
     */
    public Builder setK8SClusterId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      k8SClusterId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The resource ID assigned to the resource by Kessel Asset Inventory. 
     * </pre>
     *
     * <code>string k8s_cluster_id = 240280960 [json_name = "k8s_cluster_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return This builder for chaining.
     */
    public Builder clearK8SClusterId() {
      k8SClusterId_ = getDefaultInstance().getK8SClusterId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The resource ID assigned to the resource by Kessel Asset Inventory. 
     * </pre>
     *
     * <code>string k8s_cluster_id = 240280960 [json_name = "k8s_cluster_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param value The bytes for k8sClusterId to set.
     * @return This builder for chaining.
     */
    public Builder setK8SClusterIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      k8SClusterId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status status = 355610639 [json_name = "status", (.buf.validate.field) = { ... }</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status status = 355610639 [json_name = "status", (.buf.validate.field) = { ... }</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status status = 355610639 [json_name = "status", (.buf.validate.field) = { ... }</code>
     * @return The status.
     */
    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status getStatus() {
      org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status result = org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status.forNumber(status_);
      return result == null ? org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status status = 355610639 [json_name = "status", (.buf.validate.field) = { ... }</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000004;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail.Status status = 355610639 [json_name = "status", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000004);
      status_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail)
  }

  // @@protoc_insertion_point(class_scope:kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail)
  private static final org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail();
  }

  public static org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<K8SPolicyIsPropagatedToK8SClusterDetail>
      PARSER = new com.google.protobuf.AbstractParser<K8SPolicyIsPropagatedToK8SClusterDetail>() {
    @java.lang.Override
    public K8SPolicyIsPropagatedToK8SClusterDetail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<K8SPolicyIsPropagatedToK8SClusterDetail> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<K8SPolicyIsPropagatedToK8SClusterDetail> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

