// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta1/relationships/k8spolicy_ispropagatedto_k8scluster.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta1.relationships;

@com.google.protobuf.Generated
public interface K8SPolicyIsPropagatedToK8SClusterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SCluster)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Metadata about this resource
   * </pre>
   *
   * <code>.kessel.inventory.v1beta1.relationships.Metadata metadata = 1 [json_name = "metadata", (.buf.validate.field) = { ... }</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Metadata about this resource
   * </pre>
   *
   * <code>.kessel.inventory.v1beta1.relationships.Metadata metadata = 1 [json_name = "metadata", (.buf.validate.field) = { ... }</code>
   * @return The metadata.
   */
  org.project_kessel.api.inventory.v1beta1.relationships.Metadata getMetadata();
  /**
   * <pre>
   * Metadata about this resource
   * </pre>
   *
   * <code>.kessel.inventory.v1beta1.relationships.Metadata metadata = 1 [json_name = "metadata", (.buf.validate.field) = { ... }</code>
   */
  org.project_kessel.api.inventory.v1beta1.relationships.MetadataOrBuilder getMetadataOrBuilder();

  /**
   * <pre>
   * Write only reporter specific data
   * </pre>
   *
   * <code>.kessel.inventory.v1beta1.relationships.ReporterData reporter_data = 245278793 [json_name = "reporter_data", (.buf.validate.field) = { ... }</code>
   * @return Whether the reporterData field is set.
   */
  boolean hasReporterData();
  /**
   * <pre>
   * Write only reporter specific data
   * </pre>
   *
   * <code>.kessel.inventory.v1beta1.relationships.ReporterData reporter_data = 245278793 [json_name = "reporter_data", (.buf.validate.field) = { ... }</code>
   * @return The reporterData.
   */
  org.project_kessel.api.inventory.v1beta1.relationships.ReporterData getReporterData();
  /**
   * <pre>
   * Write only reporter specific data
   * </pre>
   *
   * <code>.kessel.inventory.v1beta1.relationships.ReporterData reporter_data = 245278793 [json_name = "reporter_data", (.buf.validate.field) = { ... }</code>
   */
  org.project_kessel.api.inventory.v1beta1.relationships.ReporterDataOrBuilder getReporterDataOrBuilder();

  /**
   * <code>.kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail relationship_data = 2122699 [json_name = "relationship_data", (.buf.validate.field) = { ... }</code>
   * @return Whether the relationshipData field is set.
   */
  boolean hasRelationshipData();
  /**
   * <code>.kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail relationship_data = 2122699 [json_name = "relationship_data", (.buf.validate.field) = { ... }</code>
   * @return The relationshipData.
   */
  org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail getRelationshipData();
  /**
   * <code>.kessel.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetail relationship_data = 2122699 [json_name = "relationship_data", (.buf.validate.field) = { ... }</code>
   */
  org.project_kessel.api.inventory.v1beta1.relationships.K8SPolicyIsPropagatedToK8SClusterDetailOrBuilder getRelationshipDataOrBuilder();
}
