// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta1/relationships/reporter_data.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta1.relationships;

/**
 * Protobuf type {@code kessel.inventory.v1beta1.relationships.ReporterData}
 */
@com.google.protobuf.Generated
public final class ReporterData extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:kessel.inventory.v1beta1.relationships.ReporterData)
    ReporterDataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      ReporterData.class.getName());
  }
  // Use ReporterData.newBuilder() to construct.
  private ReporterData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ReporterData() {
    reporterType_ = 0;
    reporterInstanceId_ = "";
    reporterVersion_ = "";
    subjectLocalResourceId_ = "";
    objectLocalResourceId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.project_kessel.api.inventory.v1beta1.relationships.ReporterDataOuterClass.internal_static_kessel_inventory_v1beta1_relationships_ReporterData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.project_kessel.api.inventory.v1beta1.relationships.ReporterDataOuterClass.internal_static_kessel_inventory_v1beta1_relationships_ReporterData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.class, org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.Builder.class);
  }

  /**
   * Protobuf enum {@code kessel.inventory.v1beta1.relationships.ReporterData.ReporterType}
   */
  public enum ReporterType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REPORTER_TYPE_UNSPECIFIED = 0;</code>
     */
    REPORTER_TYPE_UNSPECIFIED(0),
    /**
     * <code>REPORTER_TYPE_OTHER = 1;</code>
     */
    REPORTER_TYPE_OTHER(1),
    /**
     * <code>ACM = 2;</code>
     */
    ACM(2),
    /**
     * <code>HBI = 3;</code>
     */
    HBI(3),
    /**
     * <code>OCM = 4;</code>
     */
    OCM(4),
    /**
     * <code>NOTIFICATIONS = 5;</code>
     */
    NOTIFICATIONS(5),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 32,
        /* patch= */ 0,
        /* suffix= */ "",
        ReporterType.class.getName());
    }
    /**
     * <code>REPORTER_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int REPORTER_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>REPORTER_TYPE_OTHER = 1;</code>
     */
    public static final int REPORTER_TYPE_OTHER_VALUE = 1;
    /**
     * <code>ACM = 2;</code>
     */
    public static final int ACM_VALUE = 2;
    /**
     * <code>HBI = 3;</code>
     */
    public static final int HBI_VALUE = 3;
    /**
     * <code>OCM = 4;</code>
     */
    public static final int OCM_VALUE = 4;
    /**
     * <code>NOTIFICATIONS = 5;</code>
     */
    public static final int NOTIFICATIONS_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ReporterType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ReporterType forNumber(int value) {
      switch (value) {
        case 0: return REPORTER_TYPE_UNSPECIFIED;
        case 1: return REPORTER_TYPE_OTHER;
        case 2: return ACM;
        case 3: return HBI;
        case 4: return OCM;
        case 5: return NOTIFICATIONS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ReporterType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ReporterType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReporterType>() {
            public ReporterType findValueByNumber(int number) {
              return ReporterType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.getDescriptor().getEnumTypes().get(0);
    }

    private static final ReporterType[] VALUES = values();

    public static ReporterType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ReporterType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:kessel.inventory.v1beta1.relationships.ReporterData.ReporterType)
  }

  private int bitField0_;
  public static final int REPORTER_TYPE_FIELD_NUMBER = 245778393;
  private int reporterType_ = 0;
  /**
   * <code>.kessel.inventory.v1beta1.relationships.ReporterData.ReporterType reporter_type = 245778393 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for reporterType.
   */
  @java.lang.Override public int getReporterTypeValue() {
    return reporterType_;
  }
  /**
   * <code>.kessel.inventory.v1beta1.relationships.ReporterData.ReporterType reporter_type = 245778393 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
   * @return The reporterType.
   */
  @java.lang.Override public org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.ReporterType getReporterType() {
    org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.ReporterType result = org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.ReporterType.forNumber(reporterType_);
    return result == null ? org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.ReporterType.UNRECOGNIZED : result;
  }

  public static final int REPORTER_INSTANCE_ID_FIELD_NUMBER = 241085114;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reporterInstanceId_ = "";
  /**
   * <pre>
   * The ID of the instance of the reporter. This is derived from the
   * authentication mechanism, i.e. authentication token.
   * </pre>
   *
   * <code>string reporter_instance_id = 241085114 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The reporterInstanceId.
   */
  @java.lang.Override
  public java.lang.String getReporterInstanceId() {
    java.lang.Object ref = reporterInstanceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reporterInstanceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID of the instance of the reporter. This is derived from the
   * authentication mechanism, i.e. authentication token.
   * </pre>
   *
   * <code>string reporter_instance_id = 241085114 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The bytes for reporterInstanceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReporterInstanceIdBytes() {
    java.lang.Object ref = reporterInstanceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reporterInstanceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPORTER_VERSION_FIELD_NUMBER = 269629307;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reporterVersion_ = "";
  /**
   * <pre>
   * version of the reporter
   * </pre>
   *
   * <code>string reporter_version = 269629307 [json_name = "reporter_version"];</code>
   * @return The reporterVersion.
   */
  @java.lang.Override
  public java.lang.String getReporterVersion() {
    java.lang.Object ref = reporterVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reporterVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * version of the reporter
   * </pre>
   *
   * <code>string reporter_version = 269629307 [json_name = "reporter_version"];</code>
   * @return The bytes for reporterVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReporterVersionBytes() {
    java.lang.Object ref = reporterVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reporterVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIRST_REPORTED_FIELD_NUMBER = 13874817;
  private com.google.protobuf.Timestamp firstReported_;
  /**
   * <pre>
   * Date and time when the inventory item was first reported by this reporter
   * </pre>
   *
   * <code>.google.protobuf.Timestamp first_reported = 13874817 [json_name = "first_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return Whether the firstReported field is set.
   */
  @java.lang.Override
  public boolean hasFirstReported() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Date and time when the inventory item was first reported by this reporter
   * </pre>
   *
   * <code>.google.protobuf.Timestamp first_reported = 13874817 [json_name = "first_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The firstReported.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getFirstReported() {
    return firstReported_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : firstReported_;
  }
  /**
   * <pre>
   * Date and time when the inventory item was first reported by this reporter
   * </pre>
   *
   * <code>.google.protobuf.Timestamp first_reported = 13874817 [json_name = "first_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getFirstReportedOrBuilder() {
    return firstReported_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : firstReported_;
  }

  public static final int LAST_REPORTED_FIELD_NUMBER = 436473484;
  private com.google.protobuf.Timestamp lastReported_;
  /**
   * <pre>
   * Date and time when the inventory item was last updated by this reporter
   * </pre>
   *
   * <code>.google.protobuf.Timestamp last_reported = 436473484 [json_name = "last_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return Whether the lastReported field is set.
   */
  @java.lang.Override
  public boolean hasLastReported() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Date and time when the inventory item was last updated by this reporter
   * </pre>
   *
   * <code>.google.protobuf.Timestamp last_reported = 436473484 [json_name = "last_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The lastReported.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLastReported() {
    return lastReported_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastReported_;
  }
  /**
   * <pre>
   * Date and time when the inventory item was last updated by this reporter
   * </pre>
   *
   * <code>.google.protobuf.Timestamp last_reported = 436473484 [json_name = "last_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getLastReportedOrBuilder() {
    return lastReported_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastReported_;
  }

  public static final int SUBJECT_LOCAL_RESOURCE_ID_FIELD_NUMBER = 508976190;
  @SuppressWarnings("serial")
  private volatile java.lang.Object subjectLocalResourceId_ = "";
  /**
   * <pre>
   * The ID assigned by the reporter to resource which is the subject of the relationship. For example 
   * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
   * </pre>
   *
   * <code>string subject_local_resource_id = 508976190 [json_name = "subject_local_resource_id", (.buf.validate.field) = { ... }</code>
   * @return The subjectLocalResourceId.
   */
  @java.lang.Override
  public java.lang.String getSubjectLocalResourceId() {
    java.lang.Object ref = subjectLocalResourceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subjectLocalResourceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID assigned by the reporter to resource which is the subject of the relationship. For example 
   * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
   * </pre>
   *
   * <code>string subject_local_resource_id = 508976190 [json_name = "subject_local_resource_id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for subjectLocalResourceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubjectLocalResourceIdBytes() {
    java.lang.Object ref = subjectLocalResourceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subjectLocalResourceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OBJECT_LOCAL_RESOURCE_ID_FIELD_NUMBER = 508976191;
  @SuppressWarnings("serial")
  private volatile java.lang.Object objectLocalResourceId_ = "";
  /**
   * <pre>
   * The ID assigned by the reporter to resource which is the object of the relationship. For example 
   * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
   * </pre>
   *
   * <code>string object_local_resource_id = 508976191 [json_name = "object_local_resource_id", (.buf.validate.field) = { ... }</code>
   * @return The objectLocalResourceId.
   */
  @java.lang.Override
  public java.lang.String getObjectLocalResourceId() {
    java.lang.Object ref = objectLocalResourceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      objectLocalResourceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The ID assigned by the reporter to resource which is the object of the relationship. For example 
   * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
   * </pre>
   *
   * <code>string object_local_resource_id = 508976191 [json_name = "object_local_resource_id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for objectLocalResourceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectLocalResourceIdBytes() {
    java.lang.Object ref = objectLocalResourceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      objectLocalResourceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(13874817, getFirstReported());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reporterInstanceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 241085114, reporterInstanceId_);
    }
    if (reporterType_ != org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.ReporterType.REPORTER_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(245778393, reporterType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reporterVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 269629307, reporterVersion_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(436473484, getLastReported());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(subjectLocalResourceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 508976190, subjectLocalResourceId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(objectLocalResourceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 508976191, objectLocalResourceId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13874817, getFirstReported());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reporterInstanceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(241085114, reporterInstanceId_);
    }
    if (reporterType_ != org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.ReporterType.REPORTER_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(245778393, reporterType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(reporterVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(269629307, reporterVersion_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(436473484, getLastReported());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(subjectLocalResourceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(508976190, subjectLocalResourceId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(objectLocalResourceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(508976191, objectLocalResourceId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.project_kessel.api.inventory.v1beta1.relationships.ReporterData)) {
      return super.equals(obj);
    }
    org.project_kessel.api.inventory.v1beta1.relationships.ReporterData other = (org.project_kessel.api.inventory.v1beta1.relationships.ReporterData) obj;

    if (reporterType_ != other.reporterType_) return false;
    if (!getReporterInstanceId()
        .equals(other.getReporterInstanceId())) return false;
    if (!getReporterVersion()
        .equals(other.getReporterVersion())) return false;
    if (hasFirstReported() != other.hasFirstReported()) return false;
    if (hasFirstReported()) {
      if (!getFirstReported()
          .equals(other.getFirstReported())) return false;
    }
    if (hasLastReported() != other.hasLastReported()) return false;
    if (hasLastReported()) {
      if (!getLastReported()
          .equals(other.getLastReported())) return false;
    }
    if (!getSubjectLocalResourceId()
        .equals(other.getSubjectLocalResourceId())) return false;
    if (!getObjectLocalResourceId()
        .equals(other.getObjectLocalResourceId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REPORTER_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + reporterType_;
    hash = (37 * hash) + REPORTER_INSTANCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReporterInstanceId().hashCode();
    hash = (37 * hash) + REPORTER_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getReporterVersion().hashCode();
    if (hasFirstReported()) {
      hash = (37 * hash) + FIRST_REPORTED_FIELD_NUMBER;
      hash = (53 * hash) + getFirstReported().hashCode();
    }
    if (hasLastReported()) {
      hash = (37 * hash) + LAST_REPORTED_FIELD_NUMBER;
      hash = (53 * hash) + getLastReported().hashCode();
    }
    hash = (37 * hash) + SUBJECT_LOCAL_RESOURCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSubjectLocalResourceId().hashCode();
    hash = (37 * hash) + OBJECT_LOCAL_RESOURCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getObjectLocalResourceId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.project_kessel.api.inventory.v1beta1.relationships.ReporterData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.ReporterData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.ReporterData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.ReporterData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.ReporterData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.ReporterData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.ReporterData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.ReporterData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.project_kessel.api.inventory.v1beta1.relationships.ReporterData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.project_kessel.api.inventory.v1beta1.relationships.ReporterData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.ReporterData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta1.relationships.ReporterData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.project_kessel.api.inventory.v1beta1.relationships.ReporterData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kessel.inventory.v1beta1.relationships.ReporterData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kessel.inventory.v1beta1.relationships.ReporterData)
      org.project_kessel.api.inventory.v1beta1.relationships.ReporterDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta1.relationships.ReporterDataOuterClass.internal_static_kessel_inventory_v1beta1_relationships_ReporterData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.project_kessel.api.inventory.v1beta1.relationships.ReporterDataOuterClass.internal_static_kessel_inventory_v1beta1_relationships_ReporterData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.class, org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.Builder.class);
    }

    // Construct using org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetFirstReportedFieldBuilder();
        internalGetLastReportedFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      reporterType_ = 0;
      reporterInstanceId_ = "";
      reporterVersion_ = "";
      firstReported_ = null;
      if (firstReportedBuilder_ != null) {
        firstReportedBuilder_.dispose();
        firstReportedBuilder_ = null;
      }
      lastReported_ = null;
      if (lastReportedBuilder_ != null) {
        lastReportedBuilder_.dispose();
        lastReportedBuilder_ = null;
      }
      subjectLocalResourceId_ = "";
      objectLocalResourceId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.project_kessel.api.inventory.v1beta1.relationships.ReporterDataOuterClass.internal_static_kessel_inventory_v1beta1_relationships_ReporterData_descriptor;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.relationships.ReporterData getDefaultInstanceForType() {
      return org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.getDefaultInstance();
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.relationships.ReporterData build() {
      org.project_kessel.api.inventory.v1beta1.relationships.ReporterData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.relationships.ReporterData buildPartial() {
      org.project_kessel.api.inventory.v1beta1.relationships.ReporterData result = new org.project_kessel.api.inventory.v1beta1.relationships.ReporterData(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.project_kessel.api.inventory.v1beta1.relationships.ReporterData result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.reporterType_ = reporterType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.reporterInstanceId_ = reporterInstanceId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.reporterVersion_ = reporterVersion_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.firstReported_ = firstReportedBuilder_ == null
            ? firstReported_
            : firstReportedBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.lastReported_ = lastReportedBuilder_ == null
            ? lastReported_
            : lastReportedBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.subjectLocalResourceId_ = subjectLocalResourceId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.objectLocalResourceId_ = objectLocalResourceId_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.project_kessel.api.inventory.v1beta1.relationships.ReporterData) {
        return mergeFrom((org.project_kessel.api.inventory.v1beta1.relationships.ReporterData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.project_kessel.api.inventory.v1beta1.relationships.ReporterData other) {
      if (other == org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.getDefaultInstance()) return this;
      if (other.reporterType_ != 0) {
        setReporterTypeValue(other.getReporterTypeValue());
      }
      if (!other.getReporterInstanceId().isEmpty()) {
        reporterInstanceId_ = other.reporterInstanceId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getReporterVersion().isEmpty()) {
        reporterVersion_ = other.reporterVersion_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasFirstReported()) {
        mergeFirstReported(other.getFirstReported());
      }
      if (other.hasLastReported()) {
        mergeLastReported(other.getLastReported());
      }
      if (!other.getSubjectLocalResourceId().isEmpty()) {
        subjectLocalResourceId_ = other.subjectLocalResourceId_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getObjectLocalResourceId().isEmpty()) {
        objectLocalResourceId_ = other.objectLocalResourceId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 110998538: {
              input.readMessage(
                  internalGetFirstReportedFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 110998538
            case 1928680914: {
              reporterInstanceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 1928680914
            case 1966227144: {
              reporterType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 1966227144
            case -2137932838: {
              reporterVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case -2137932838
            case -803179422: {
              input.readMessage(
                  internalGetLastReportedFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case -803179422
            case -223157774: {
              subjectLocalResourceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case -223157774
            case -223157766: {
              objectLocalResourceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case -223157766
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int reporterType_ = 0;
    /**
     * <code>.kessel.inventory.v1beta1.relationships.ReporterData.ReporterType reporter_type = 245778393 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
     * @return The enum numeric value on the wire for reporterType.
     */
    @java.lang.Override public int getReporterTypeValue() {
      return reporterType_;
    }
    /**
     * <code>.kessel.inventory.v1beta1.relationships.ReporterData.ReporterType reporter_type = 245778393 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
     * @param value The enum numeric value on the wire for reporterType to set.
     * @return This builder for chaining.
     */
    public Builder setReporterTypeValue(int value) {
      reporterType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta1.relationships.ReporterData.ReporterType reporter_type = 245778393 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
     * @return The reporterType.
     */
    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.ReporterType getReporterType() {
      org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.ReporterType result = org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.ReporterType.forNumber(reporterType_);
      return result == null ? org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.ReporterType.UNRECOGNIZED : result;
    }
    /**
     * <code>.kessel.inventory.v1beta1.relationships.ReporterData.ReporterType reporter_type = 245778393 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
     * @param value The reporterType to set.
     * @return This builder for chaining.
     */
    public Builder setReporterType(org.project_kessel.api.inventory.v1beta1.relationships.ReporterData.ReporterType value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      reporterType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta1.relationships.ReporterData.ReporterType reporter_type = 245778393 [json_name = "reporter_type", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearReporterType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      reporterType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object reporterInstanceId_ = "";
    /**
     * <pre>
     * The ID of the instance of the reporter. This is derived from the
     * authentication mechanism, i.e. authentication token.
     * </pre>
     *
     * <code>string reporter_instance_id = 241085114 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return The reporterInstanceId.
     */
    public java.lang.String getReporterInstanceId() {
      java.lang.Object ref = reporterInstanceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reporterInstanceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID of the instance of the reporter. This is derived from the
     * authentication mechanism, i.e. authentication token.
     * </pre>
     *
     * <code>string reporter_instance_id = 241085114 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return The bytes for reporterInstanceId.
     */
    public com.google.protobuf.ByteString
        getReporterInstanceIdBytes() {
      java.lang.Object ref = reporterInstanceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reporterInstanceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID of the instance of the reporter. This is derived from the
     * authentication mechanism, i.e. authentication token.
     * </pre>
     *
     * <code>string reporter_instance_id = 241085114 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param value The reporterInstanceId to set.
     * @return This builder for chaining.
     */
    public Builder setReporterInstanceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reporterInstanceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the instance of the reporter. This is derived from the
     * authentication mechanism, i.e. authentication token.
     * </pre>
     *
     * <code>string reporter_instance_id = 241085114 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return This builder for chaining.
     */
    public Builder clearReporterInstanceId() {
      reporterInstanceId_ = getDefaultInstance().getReporterInstanceId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID of the instance of the reporter. This is derived from the
     * authentication mechanism, i.e. authentication token.
     * </pre>
     *
     * <code>string reporter_instance_id = 241085114 [json_name = "reporter_instance_id", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @param value The bytes for reporterInstanceId to set.
     * @return This builder for chaining.
     */
    public Builder setReporterInstanceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reporterInstanceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object reporterVersion_ = "";
    /**
     * <pre>
     * version of the reporter
     * </pre>
     *
     * <code>string reporter_version = 269629307 [json_name = "reporter_version"];</code>
     * @return The reporterVersion.
     */
    public java.lang.String getReporterVersion() {
      java.lang.Object ref = reporterVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reporterVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * version of the reporter
     * </pre>
     *
     * <code>string reporter_version = 269629307 [json_name = "reporter_version"];</code>
     * @return The bytes for reporterVersion.
     */
    public com.google.protobuf.ByteString
        getReporterVersionBytes() {
      java.lang.Object ref = reporterVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reporterVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * version of the reporter
     * </pre>
     *
     * <code>string reporter_version = 269629307 [json_name = "reporter_version"];</code>
     * @param value The reporterVersion to set.
     * @return This builder for chaining.
     */
    public Builder setReporterVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reporterVersion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * version of the reporter
     * </pre>
     *
     * <code>string reporter_version = 269629307 [json_name = "reporter_version"];</code>
     * @return This builder for chaining.
     */
    public Builder clearReporterVersion() {
      reporterVersion_ = getDefaultInstance().getReporterVersion();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * version of the reporter
     * </pre>
     *
     * <code>string reporter_version = 269629307 [json_name = "reporter_version"];</code>
     * @param value The bytes for reporterVersion to set.
     * @return This builder for chaining.
     */
    public Builder setReporterVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reporterVersion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp firstReported_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> firstReportedBuilder_;
    /**
     * <pre>
     * Date and time when the inventory item was first reported by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp first_reported = 13874817 [json_name = "first_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return Whether the firstReported field is set.
     */
    public boolean hasFirstReported() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Date and time when the inventory item was first reported by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp first_reported = 13874817 [json_name = "first_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return The firstReported.
     */
    public com.google.protobuf.Timestamp getFirstReported() {
      if (firstReportedBuilder_ == null) {
        return firstReported_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : firstReported_;
      } else {
        return firstReportedBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Date and time when the inventory item was first reported by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp first_reported = 13874817 [json_name = "first_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public Builder setFirstReported(com.google.protobuf.Timestamp value) {
      if (firstReportedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        firstReported_ = value;
      } else {
        firstReportedBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Date and time when the inventory item was first reported by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp first_reported = 13874817 [json_name = "first_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public Builder setFirstReported(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (firstReportedBuilder_ == null) {
        firstReported_ = builderForValue.build();
      } else {
        firstReportedBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Date and time when the inventory item was first reported by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp first_reported = 13874817 [json_name = "first_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public Builder mergeFirstReported(com.google.protobuf.Timestamp value) {
      if (firstReportedBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          firstReported_ != null &&
          firstReported_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getFirstReportedBuilder().mergeFrom(value);
        } else {
          firstReported_ = value;
        }
      } else {
        firstReportedBuilder_.mergeFrom(value);
      }
      if (firstReported_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Date and time when the inventory item was first reported by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp first_reported = 13874817 [json_name = "first_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public Builder clearFirstReported() {
      bitField0_ = (bitField0_ & ~0x00000008);
      firstReported_ = null;
      if (firstReportedBuilder_ != null) {
        firstReportedBuilder_.dispose();
        firstReportedBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Date and time when the inventory item was first reported by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp first_reported = 13874817 [json_name = "first_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public com.google.protobuf.Timestamp.Builder getFirstReportedBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetFirstReportedFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Date and time when the inventory item was first reported by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp first_reported = 13874817 [json_name = "first_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getFirstReportedOrBuilder() {
      if (firstReportedBuilder_ != null) {
        return firstReportedBuilder_.getMessageOrBuilder();
      } else {
        return firstReported_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : firstReported_;
      }
    }
    /**
     * <pre>
     * Date and time when the inventory item was first reported by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp first_reported = 13874817 [json_name = "first_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetFirstReportedFieldBuilder() {
      if (firstReportedBuilder_ == null) {
        firstReportedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getFirstReported(),
                getParentForChildren(),
                isClean());
        firstReported_ = null;
      }
      return firstReportedBuilder_;
    }

    private com.google.protobuf.Timestamp lastReported_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastReportedBuilder_;
    /**
     * <pre>
     * Date and time when the inventory item was last updated by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_reported = 436473484 [json_name = "last_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return Whether the lastReported field is set.
     */
    public boolean hasLastReported() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Date and time when the inventory item was last updated by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_reported = 436473484 [json_name = "last_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     * @return The lastReported.
     */
    public com.google.protobuf.Timestamp getLastReported() {
      if (lastReportedBuilder_ == null) {
        return lastReported_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastReported_;
      } else {
        return lastReportedBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Date and time when the inventory item was last updated by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_reported = 436473484 [json_name = "last_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public Builder setLastReported(com.google.protobuf.Timestamp value) {
      if (lastReportedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastReported_ = value;
      } else {
        lastReportedBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Date and time when the inventory item was last updated by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_reported = 436473484 [json_name = "last_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public Builder setLastReported(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastReportedBuilder_ == null) {
        lastReported_ = builderForValue.build();
      } else {
        lastReportedBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Date and time when the inventory item was last updated by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_reported = 436473484 [json_name = "last_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public Builder mergeLastReported(com.google.protobuf.Timestamp value) {
      if (lastReportedBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          lastReported_ != null &&
          lastReported_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getLastReportedBuilder().mergeFrom(value);
        } else {
          lastReported_ = value;
        }
      } else {
        lastReportedBuilder_.mergeFrom(value);
      }
      if (lastReported_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Date and time when the inventory item was last updated by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_reported = 436473484 [json_name = "last_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public Builder clearLastReported() {
      bitField0_ = (bitField0_ & ~0x00000010);
      lastReported_ = null;
      if (lastReportedBuilder_ != null) {
        lastReportedBuilder_.dispose();
        lastReportedBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Date and time when the inventory item was last updated by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_reported = 436473484 [json_name = "last_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastReportedBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetLastReportedFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Date and time when the inventory item was last updated by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_reported = 436473484 [json_name = "last_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastReportedOrBuilder() {
      if (lastReportedBuilder_ != null) {
        return lastReportedBuilder_.getMessageOrBuilder();
      } else {
        return lastReported_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastReported_;
      }
    }
    /**
     * <pre>
     * Date and time when the inventory item was last updated by this reporter
     * </pre>
     *
     * <code>.google.protobuf.Timestamp last_reported = 436473484 [json_name = "last_reported", (.google.api.field_behavior) = OUTPUT_ONLY];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetLastReportedFieldBuilder() {
      if (lastReportedBuilder_ == null) {
        lastReportedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastReported(),
                getParentForChildren(),
                isClean());
        lastReported_ = null;
      }
      return lastReportedBuilder_;
    }

    private java.lang.Object subjectLocalResourceId_ = "";
    /**
     * <pre>
     * The ID assigned by the reporter to resource which is the subject of the relationship. For example 
     * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string subject_local_resource_id = 508976190 [json_name = "subject_local_resource_id", (.buf.validate.field) = { ... }</code>
     * @return The subjectLocalResourceId.
     */
    public java.lang.String getSubjectLocalResourceId() {
      java.lang.Object ref = subjectLocalResourceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subjectLocalResourceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID assigned by the reporter to resource which is the subject of the relationship. For example 
     * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string subject_local_resource_id = 508976190 [json_name = "subject_local_resource_id", (.buf.validate.field) = { ... }</code>
     * @return The bytes for subjectLocalResourceId.
     */
    public com.google.protobuf.ByteString
        getSubjectLocalResourceIdBytes() {
      java.lang.Object ref = subjectLocalResourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subjectLocalResourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID assigned by the reporter to resource which is the subject of the relationship. For example 
     * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string subject_local_resource_id = 508976190 [json_name = "subject_local_resource_id", (.buf.validate.field) = { ... }</code>
     * @param value The subjectLocalResourceId to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectLocalResourceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      subjectLocalResourceId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID assigned by the reporter to resource which is the subject of the relationship. For example 
     * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string subject_local_resource_id = 508976190 [json_name = "subject_local_resource_id", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearSubjectLocalResourceId() {
      subjectLocalResourceId_ = getDefaultInstance().getSubjectLocalResourceId();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID assigned by the reporter to resource which is the subject of the relationship. For example 
     * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string subject_local_resource_id = 508976190 [json_name = "subject_local_resource_id", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for subjectLocalResourceId to set.
     * @return This builder for chaining.
     */
    public Builder setSubjectLocalResourceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      subjectLocalResourceId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object objectLocalResourceId_ = "";
    /**
     * <pre>
     * The ID assigned by the reporter to resource which is the object of the relationship. For example 
     * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string object_local_resource_id = 508976191 [json_name = "object_local_resource_id", (.buf.validate.field) = { ... }</code>
     * @return The objectLocalResourceId.
     */
    public java.lang.String getObjectLocalResourceId() {
      java.lang.Object ref = objectLocalResourceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        objectLocalResourceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The ID assigned by the reporter to resource which is the object of the relationship. For example 
     * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string object_local_resource_id = 508976191 [json_name = "object_local_resource_id", (.buf.validate.field) = { ... }</code>
     * @return The bytes for objectLocalResourceId.
     */
    public com.google.protobuf.ByteString
        getObjectLocalResourceIdBytes() {
      java.lang.Object ref = objectLocalResourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectLocalResourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The ID assigned by the reporter to resource which is the object of the relationship. For example 
     * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string object_local_resource_id = 508976191 [json_name = "object_local_resource_id", (.buf.validate.field) = { ... }</code>
     * @param value The objectLocalResourceId to set.
     * @return This builder for chaining.
     */
    public Builder setObjectLocalResourceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      objectLocalResourceId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID assigned by the reporter to resource which is the object of the relationship. For example 
     * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string object_local_resource_id = 508976191 [json_name = "object_local_resource_id", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearObjectLocalResourceId() {
      objectLocalResourceId_ = getDefaultInstance().getObjectLocalResourceId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The ID assigned by the reporter to resource which is the object of the relationship. For example 
     * OCM cluster ID, HBI's host id, or ACM managed cluster name etc.
     * </pre>
     *
     * <code>string object_local_resource_id = 508976191 [json_name = "object_local_resource_id", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for objectLocalResourceId to set.
     * @return This builder for chaining.
     */
    public Builder setObjectLocalResourceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      objectLocalResourceId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:kessel.inventory.v1beta1.relationships.ReporterData)
  }

  // @@protoc_insertion_point(class_scope:kessel.inventory.v1beta1.relationships.ReporterData)
  private static final org.project_kessel.api.inventory.v1beta1.relationships.ReporterData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.project_kessel.api.inventory.v1beta1.relationships.ReporterData();
  }

  public static org.project_kessel.api.inventory.v1beta1.relationships.ReporterData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReporterData>
      PARSER = new com.google.protobuf.AbstractParser<ReporterData>() {
    @java.lang.Override
    public ReporterData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReporterData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReporterData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta1.relationships.ReporterData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

