// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/check_self_request.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

@com.google.protobuf.Generated
public interface CheckSelfRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta2.CheckSelfRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required parameters (from an authz perspective)
   * - resource type and id
   * - permission (cannot be derived from the type as a type may have multiple 'read' permissions. Ex: https://github.com/RedHatInsights/rbac-config/blob/master/configs/prod/schemas/src/notifications.ksl#L31)
   *
   * The subject is implicitly the caller, as determined by the authentication
   * context, instead of being provided as a SubjectReference.
   * </pre>
   *
   * <code>.kessel.inventory.v1beta2.ResourceReference object = 1 [json_name = "object", (.buf.validate.field) = { ... }</code>
   * @return Whether the object field is set.
   */
  boolean hasObject();
  /**
   * <pre>
   * Required parameters (from an authz perspective)
   * - resource type and id
   * - permission (cannot be derived from the type as a type may have multiple 'read' permissions. Ex: https://github.com/RedHatInsights/rbac-config/blob/master/configs/prod/schemas/src/notifications.ksl#L31)
   *
   * The subject is implicitly the caller, as determined by the authentication
   * context, instead of being provided as a SubjectReference.
   * </pre>
   *
   * <code>.kessel.inventory.v1beta2.ResourceReference object = 1 [json_name = "object", (.buf.validate.field) = { ... }</code>
   * @return The object.
   */
  org.project_kessel.api.inventory.v1beta2.ResourceReference getObject();
  /**
   * <pre>
   * Required parameters (from an authz perspective)
   * - resource type and id
   * - permission (cannot be derived from the type as a type may have multiple 'read' permissions. Ex: https://github.com/RedHatInsights/rbac-config/blob/master/configs/prod/schemas/src/notifications.ksl#L31)
   *
   * The subject is implicitly the caller, as determined by the authentication
   * context, instead of being provided as a SubjectReference.
   * </pre>
   *
   * <code>.kessel.inventory.v1beta2.ResourceReference object = 1 [json_name = "object", (.buf.validate.field) = { ... }</code>
   */
  org.project_kessel.api.inventory.v1beta2.ResourceReferenceOrBuilder getObjectOrBuilder();

  /**
   * <code>string relation = 2 [json_name = "relation", (.buf.validate.field) = { ... }</code>
   * @return The relation.
   */
  java.lang.String getRelation();
  /**
   * <code>string relation = 2 [json_name = "relation", (.buf.validate.field) = { ... }</code>
   * @return The bytes for relation.
   */
  com.google.protobuf.ByteString
      getRelationBytes();

  /**
   * <code>optional .kessel.inventory.v1beta2.Consistency consistency = 3 [json_name = "consistency"];</code>
   * @return Whether the consistency field is set.
   */
  boolean hasConsistency();
  /**
   * <code>optional .kessel.inventory.v1beta2.Consistency consistency = 3 [json_name = "consistency"];</code>
   * @return The consistency.
   */
  org.project_kessel.api.inventory.v1beta2.Consistency getConsistency();
  /**
   * <code>optional .kessel.inventory.v1beta2.Consistency consistency = 3 [json_name = "consistency"];</code>
   */
  org.project_kessel.api.inventory.v1beta2.ConsistencyOrBuilder getConsistencyOrBuilder();
}
