// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/check_for_update_bulk_response.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

/**
 * <pre>
 * CheckForUpdateBulkResponseItem represents the result of a single check-for-update.
 * </pre>
 *
 * Protobuf type {@code kessel.inventory.v1beta2.CheckForUpdateBulkResponseItem}
 */
@com.google.protobuf.Generated
public final class CheckForUpdateBulkResponseItem extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:kessel.inventory.v1beta2.CheckForUpdateBulkResponseItem)
    CheckForUpdateBulkResponseItemOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      CheckForUpdateBulkResponseItem.class.getName());
  }
  // Use CheckForUpdateBulkResponseItem.newBuilder() to construct.
  private CheckForUpdateBulkResponseItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CheckForUpdateBulkResponseItem() {
    allowed_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseOuterClass.internal_static_kessel_inventory_v1beta2_CheckForUpdateBulkResponseItem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseOuterClass.internal_static_kessel_inventory_v1beta2_CheckForUpdateBulkResponseItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem.class, org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem.Builder.class);
  }

  public static final int ALLOWED_FIELD_NUMBER = 1;
  private int allowed_ = 0;
  /**
   * <code>.kessel.inventory.v1beta2.Allowed allowed = 1 [json_name = "allowed"];</code>
   * @return The enum numeric value on the wire for allowed.
   */
  @java.lang.Override public int getAllowedValue() {
    return allowed_;
  }
  /**
   * <code>.kessel.inventory.v1beta2.Allowed allowed = 1 [json_name = "allowed"];</code>
   * @return The allowed.
   */
  @java.lang.Override public org.project_kessel.api.inventory.v1beta2.Allowed getAllowed() {
    org.project_kessel.api.inventory.v1beta2.Allowed result = org.project_kessel.api.inventory.v1beta2.Allowed.forNumber(allowed_);
    return result == null ? org.project_kessel.api.inventory.v1beta2.Allowed.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (allowed_ != org.project_kessel.api.inventory.v1beta2.Allowed.ALLOWED_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, allowed_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (allowed_ != org.project_kessel.api.inventory.v1beta2.Allowed.ALLOWED_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, allowed_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem)) {
      return super.equals(obj);
    }
    org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem other = (org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem) obj;

    if (allowed_ != other.allowed_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALLOWED_FIELD_NUMBER;
    hash = (53 * hash) + allowed_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * CheckForUpdateBulkResponseItem represents the result of a single check-for-update.
   * </pre>
   *
   * Protobuf type {@code kessel.inventory.v1beta2.CheckForUpdateBulkResponseItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kessel.inventory.v1beta2.CheckForUpdateBulkResponseItem)
      org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseOuterClass.internal_static_kessel_inventory_v1beta2_CheckForUpdateBulkResponseItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseOuterClass.internal_static_kessel_inventory_v1beta2_CheckForUpdateBulkResponseItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem.class, org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem.Builder.class);
    }

    // Construct using org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      allowed_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseOuterClass.internal_static_kessel_inventory_v1beta2_CheckForUpdateBulkResponseItem_descriptor;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem getDefaultInstanceForType() {
      return org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem.getDefaultInstance();
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem build() {
      org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem buildPartial() {
      org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem result = new org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.allowed_ = allowed_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem) {
        return mergeFrom((org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem other) {
      if (other == org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem.getDefaultInstance()) return this;
      if (other.allowed_ != 0) {
        setAllowedValue(other.getAllowedValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              allowed_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int allowed_ = 0;
    /**
     * <code>.kessel.inventory.v1beta2.Allowed allowed = 1 [json_name = "allowed"];</code>
     * @return The enum numeric value on the wire for allowed.
     */
    @java.lang.Override public int getAllowedValue() {
      return allowed_;
    }
    /**
     * <code>.kessel.inventory.v1beta2.Allowed allowed = 1 [json_name = "allowed"];</code>
     * @param value The enum numeric value on the wire for allowed to set.
     * @return This builder for chaining.
     */
    public Builder setAllowedValue(int value) {
      allowed_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta2.Allowed allowed = 1 [json_name = "allowed"];</code>
     * @return The allowed.
     */
    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta2.Allowed getAllowed() {
      org.project_kessel.api.inventory.v1beta2.Allowed result = org.project_kessel.api.inventory.v1beta2.Allowed.forNumber(allowed_);
      return result == null ? org.project_kessel.api.inventory.v1beta2.Allowed.UNRECOGNIZED : result;
    }
    /**
     * <code>.kessel.inventory.v1beta2.Allowed allowed = 1 [json_name = "allowed"];</code>
     * @param value The allowed to set.
     * @return This builder for chaining.
     */
    public Builder setAllowed(org.project_kessel.api.inventory.v1beta2.Allowed value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000001;
      allowed_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.kessel.inventory.v1beta2.Allowed allowed = 1 [json_name = "allowed"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAllowed() {
      bitField0_ = (bitField0_ & ~0x00000001);
      allowed_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:kessel.inventory.v1beta2.CheckForUpdateBulkResponseItem)
  }

  // @@protoc_insertion_point(class_scope:kessel.inventory.v1beta2.CheckForUpdateBulkResponseItem)
  private static final org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem();
  }

  public static org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckForUpdateBulkResponseItem>
      PARSER = new com.google.protobuf.AbstractParser<CheckForUpdateBulkResponseItem>() {
    @java.lang.Override
    public CheckForUpdateBulkResponseItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CheckForUpdateBulkResponseItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckForUpdateBulkResponseItem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta2.CheckForUpdateBulkResponseItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

