// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/check_for_update_response.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

@com.google.protobuf.Generated
public final class CheckForUpdateResponseOuterClass {
  private CheckForUpdateResponseOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      CheckForUpdateResponseOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_inventory_v1beta2_CheckForUpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kessel_inventory_v1beta2_CheckForUpdateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8kessel/inventory/v1beta2/check_for_upd" +
      "ate_response.proto\022\030kessel.inventory.v1b" +
      "eta2\032&kessel/inventory/v1beta2/allowed.p" +
      "roto\0320kessel/inventory/v1beta2/consisten" +
      "cy_token.proto\"\256\001\n\026CheckForUpdateRespons" +
      "e\022;\n\007allowed\030\001 \001(\0162!.kessel.inventory.v1" +
      "beta2.AllowedR\007allowed\022W\n\021consistency_to" +
      "ken\030\002 \001(\0132*.kessel.inventory.v1beta2.Con" +
      "sistencyTokenR\020consistencyTokenBr\n(org.p" +
      "roject_kessel.api.inventory.v1beta2P\001ZDg" +
      "ithub.com/project-kessel/inventory-api/a" +
      "pi/kessel/inventory/v1beta2b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.project_kessel.api.inventory.v1beta2.AllowedOuterClass.getDescriptor(),
          org.project_kessel.api.inventory.v1beta2.ConsistencyTokenOuterClass.getDescriptor(),
        });
    internal_static_kessel_inventory_v1beta2_CheckForUpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kessel_inventory_v1beta2_CheckForUpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_kessel_inventory_v1beta2_CheckForUpdateResponse_descriptor,
        new java.lang.String[] { "Allowed", "ConsistencyToken", });
    descriptor.resolveAllFeaturesImmutable();
    org.project_kessel.api.inventory.v1beta2.AllowedOuterClass.getDescriptor();
    org.project_kessel.api.inventory.v1beta2.ConsistencyTokenOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
