// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/check_bulk_response.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

@com.google.protobuf.Generated
public interface CheckBulkResponseItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta2.CheckBulkResponseItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kessel.inventory.v1beta2.Allowed allowed = 1 [json_name = "allowed"];</code>
   * @return The enum numeric value on the wire for allowed.
   */
  int getAllowedValue();
  /**
   * <code>.kessel.inventory.v1beta2.Allowed allowed = 1 [json_name = "allowed"];</code>
   * @return The allowed.
   */
  org.project_kessel.api.inventory.v1beta2.Allowed getAllowed();
}
