// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/consistency_token.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

@com.google.protobuf.Generated
public interface ConsistencyTokenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta2.ConsistencyToken)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1 [json_name = "token", (.buf.validate.field) = { ... }</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1 [json_name = "token", (.buf.validate.field) = { ... }</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
