// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/create_tuples_request.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

@com.google.protobuf.Generated
public interface CreateTuplesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta2.CreateTuplesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Whether or not the request should ignore existing tuples (true),
   * or if the request should fail if the same tuple already exists (false).
   * Defaults to false.
   * </pre>
   *
   * <code>bool upsert = 1 [json_name = "upsert"];</code>
   * @return The upsert.
   */
  boolean getUpsert();

  /**
   * <code>repeated .kessel.inventory.v1beta2.Relationship tuples = 2 [json_name = "tuples"];</code>
   */
  java.util.List<org.project_kessel.api.inventory.v1beta2.Relationship> 
      getTuplesList();
  /**
   * <code>repeated .kessel.inventory.v1beta2.Relationship tuples = 2 [json_name = "tuples"];</code>
   */
  org.project_kessel.api.inventory.v1beta2.Relationship getTuples(int index);
  /**
   * <code>repeated .kessel.inventory.v1beta2.Relationship tuples = 2 [json_name = "tuples"];</code>
   */
  int getTuplesCount();
  /**
   * <code>repeated .kessel.inventory.v1beta2.Relationship tuples = 2 [json_name = "tuples"];</code>
   */
  java.util.List<? extends org.project_kessel.api.inventory.v1beta2.RelationshipOrBuilder> 
      getTuplesOrBuilderList();
  /**
   * <code>repeated .kessel.inventory.v1beta2.Relationship tuples = 2 [json_name = "tuples"];</code>
   */
  org.project_kessel.api.inventory.v1beta2.RelationshipOrBuilder getTuplesOrBuilder(
      int index);

  /**
   * <code>optional .kessel.inventory.v1beta2.RelationFencingCheck fencing_check = 3 [json_name = "fencingCheck"];</code>
   * @return Whether the fencingCheck field is set.
   */
  boolean hasFencingCheck();
  /**
   * <code>optional .kessel.inventory.v1beta2.RelationFencingCheck fencing_check = 3 [json_name = "fencingCheck"];</code>
   * @return The fencingCheck.
   */
  org.project_kessel.api.inventory.v1beta2.RelationFencingCheck getFencingCheck();
  /**
   * <code>optional .kessel.inventory.v1beta2.RelationFencingCheck fencing_check = 3 [json_name = "fencingCheck"];</code>
   */
  org.project_kessel.api.inventory.v1beta2.RelationFencingCheckOrBuilder getFencingCheckOrBuilder();
}
