// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/create_tuples_response.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

@com.google.protobuf.Generated
public final class CreateTuplesResponseOuterClass {
  private CreateTuplesResponseOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      CreateTuplesResponseOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_inventory_v1beta2_CreateTuplesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kessel_inventory_v1beta2_CreateTuplesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5kessel/inventory/v1beta2/create_tuples" +
      "_response.proto\022\030kessel.inventory.v1beta" +
      "2\0320kessel/inventory/v1beta2/consistency_" +
      "token.proto\"o\n\024CreateTuplesResponse\022W\n\021c" +
      "onsistency_token\030\001 \001(\0132*.kessel.inventor" +
      "y.v1beta2.ConsistencyTokenR\020consistencyT" +
      "okenBr\n(org.project_kessel.api.inventory" +
      ".v1beta2P\001ZDgithub.com/project-kessel/in" +
      "ventory-api/api/kessel/inventory/v1beta2" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.project_kessel.api.inventory.v1beta2.ConsistencyTokenOuterClass.getDescriptor(),
        });
    internal_static_kessel_inventory_v1beta2_CreateTuplesResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kessel_inventory_v1beta2_CreateTuplesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_kessel_inventory_v1beta2_CreateTuplesResponse_descriptor,
        new java.lang.String[] { "ConsistencyToken", });
    descriptor.resolveAllFeaturesImmutable();
    org.project_kessel.api.inventory.v1beta2.ConsistencyTokenOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
