// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/delete_tuples_request.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

@com.google.protobuf.Generated
public interface DeleteTuplesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta2.DeleteTuplesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kessel.inventory.v1beta2.RelationTupleFilter filter = 1 [json_name = "filter", (.buf.validate.field) = { ... }</code>
   * @return Whether the filter field is set.
   */
  boolean hasFilter();
  /**
   * <code>.kessel.inventory.v1beta2.RelationTupleFilter filter = 1 [json_name = "filter", (.buf.validate.field) = { ... }</code>
   * @return The filter.
   */
  org.project_kessel.api.inventory.v1beta2.RelationTupleFilter getFilter();
  /**
   * <code>.kessel.inventory.v1beta2.RelationTupleFilter filter = 1 [json_name = "filter", (.buf.validate.field) = { ... }</code>
   */
  org.project_kessel.api.inventory.v1beta2.RelationTupleFilterOrBuilder getFilterOrBuilder();

  /**
   * <code>optional .kessel.inventory.v1beta2.RelationFencingCheck fencing_check = 2 [json_name = "fencingCheck"];</code>
   * @return Whether the fencingCheck field is set.
   */
  boolean hasFencingCheck();
  /**
   * <code>optional .kessel.inventory.v1beta2.RelationFencingCheck fencing_check = 2 [json_name = "fencingCheck"];</code>
   * @return The fencingCheck.
   */
  org.project_kessel.api.inventory.v1beta2.RelationFencingCheck getFencingCheck();
  /**
   * <code>optional .kessel.inventory.v1beta2.RelationFencingCheck fencing_check = 2 [json_name = "fencingCheck"];</code>
   */
  org.project_kessel.api.inventory.v1beta2.RelationFencingCheckOrBuilder getFencingCheckOrBuilder();
}
