// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/read_tuples_response.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

@com.google.protobuf.Generated
public interface ReadTuplesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta2.ReadTuplesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kessel.inventory.v1beta2.Relationship tuple = 1 [json_name = "tuple"];</code>
   * @return Whether the tuple field is set.
   */
  boolean hasTuple();
  /**
   * <code>.kessel.inventory.v1beta2.Relationship tuple = 1 [json_name = "tuple"];</code>
   * @return The tuple.
   */
  org.project_kessel.api.inventory.v1beta2.Relationship getTuple();
  /**
   * <code>.kessel.inventory.v1beta2.Relationship tuple = 1 [json_name = "tuple"];</code>
   */
  org.project_kessel.api.inventory.v1beta2.RelationshipOrBuilder getTupleOrBuilder();

  /**
   * <code>.kessel.inventory.v1beta2.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   * @return Whether the pagination field is set.
   */
  boolean hasPagination();
  /**
   * <code>.kessel.inventory.v1beta2.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   * @return The pagination.
   */
  org.project_kessel.api.inventory.v1beta2.ResponsePagination getPagination();
  /**
   * <code>.kessel.inventory.v1beta2.ResponsePagination pagination = 2 [json_name = "pagination"];</code>
   */
  org.project_kessel.api.inventory.v1beta2.ResponsePaginationOrBuilder getPaginationOrBuilder();

  /**
   * <code>.kessel.inventory.v1beta2.ConsistencyToken consistency_token = 3 [json_name = "consistencyToken"];</code>
   * @return Whether the consistencyToken field is set.
   */
  boolean hasConsistencyToken();
  /**
   * <code>.kessel.inventory.v1beta2.ConsistencyToken consistency_token = 3 [json_name = "consistencyToken"];</code>
   * @return The consistencyToken.
   */
  org.project_kessel.api.inventory.v1beta2.ConsistencyToken getConsistencyToken();
  /**
   * <code>.kessel.inventory.v1beta2.ConsistencyToken consistency_token = 3 [json_name = "consistencyToken"];</code>
   */
  org.project_kessel.api.inventory.v1beta2.ConsistencyTokenOrBuilder getConsistencyTokenOrBuilder();
}
