// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/relation_object_reference.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

@com.google.protobuf.Generated
public interface RelationObjectReferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta2.RelationObjectReference)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kessel.inventory.v1beta2.RelationObjectType type = 1 [json_name = "type", (.buf.validate.field) = { ... }</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>.kessel.inventory.v1beta2.RelationObjectType type = 1 [json_name = "type", (.buf.validate.field) = { ... }</code>
   * @return The type.
   */
  org.project_kessel.api.inventory.v1beta2.RelationObjectType getType();
  /**
   * <code>.kessel.inventory.v1beta2.RelationObjectType type = 1 [json_name = "type", (.buf.validate.field) = { ... }</code>
   */
  org.project_kessel.api.inventory.v1beta2.RelationObjectTypeOrBuilder getTypeOrBuilder();

  /**
   * <code>string id = 2 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
