// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/relation_object_type.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

@com.google.protobuf.Generated
public interface RelationObjectTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta2.RelationObjectType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string namespace = 1 [json_name = "namespace", (.buf.validate.field) = { ... }</code>
   * @return The namespace.
   */
  java.lang.String getNamespace();
  /**
   * <code>string namespace = 1 [json_name = "namespace", (.buf.validate.field) = { ... }</code>
   * @return The bytes for namespace.
   */
  com.google.protobuf.ByteString
      getNamespaceBytes();

  /**
   * <code>string name = 2 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
