// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/representation_type.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

/**
 * Protobuf type {@code kessel.inventory.v1beta2.RepresentationType}
 */
@com.google.protobuf.Generated
public final class RepresentationType extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:kessel.inventory.v1beta2.RepresentationType)
    RepresentationTypeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      RepresentationType.class.getName());
  }
  // Use RepresentationType.newBuilder() to construct.
  private RepresentationType(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RepresentationType() {
    resourceType_ = "";
    reporterType_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.project_kessel.api.inventory.v1beta2.RepresentationTypeOuterClass.internal_static_kessel_inventory_v1beta2_RepresentationType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.project_kessel.api.inventory.v1beta2.RepresentationTypeOuterClass.internal_static_kessel_inventory_v1beta2_RepresentationType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.project_kessel.api.inventory.v1beta2.RepresentationType.class, org.project_kessel.api.inventory.v1beta2.RepresentationType.Builder.class);
  }

  private int bitField0_;
  public static final int RESOURCE_TYPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resourceType_ = "";
  /**
   * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
   * @return The resourceType.
   */
  @java.lang.Override
  public java.lang.String getResourceType() {
    java.lang.Object ref = resourceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceType_ = s;
      return s;
    }
  }
  /**
   * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
   * @return The bytes for resourceType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceTypeBytes() {
    java.lang.Object ref = resourceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPORTER_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object reporterType_ = "";
  /**
   * <code>optional string reporter_type = 2 [json_name = "reporterType", (.buf.validate.field) = { ... }</code>
   * @return Whether the reporterType field is set.
   */
  @java.lang.Override
  public boolean hasReporterType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string reporter_type = 2 [json_name = "reporterType", (.buf.validate.field) = { ... }</code>
   * @return The reporterType.
   */
  @java.lang.Override
  public java.lang.String getReporterType() {
    java.lang.Object ref = reporterType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reporterType_ = s;
      return s;
    }
  }
  /**
   * <code>optional string reporter_type = 2 [json_name = "reporterType", (.buf.validate.field) = { ... }</code>
   * @return The bytes for reporterType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReporterTypeBytes() {
    java.lang.Object ref = reporterType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reporterType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourceType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, resourceType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, reporterType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourceType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, resourceType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, reporterType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.project_kessel.api.inventory.v1beta2.RepresentationType)) {
      return super.equals(obj);
    }
    org.project_kessel.api.inventory.v1beta2.RepresentationType other = (org.project_kessel.api.inventory.v1beta2.RepresentationType) obj;

    if (!getResourceType()
        .equals(other.getResourceType())) return false;
    if (hasReporterType() != other.hasReporterType()) return false;
    if (hasReporterType()) {
      if (!getReporterType()
          .equals(other.getReporterType())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESOURCE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getResourceType().hashCode();
    if (hasReporterType()) {
      hash = (37 * hash) + REPORTER_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getReporterType().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.project_kessel.api.inventory.v1beta2.RepresentationType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta2.RepresentationType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta2.RepresentationType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta2.RepresentationType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta2.RepresentationType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta2.RepresentationType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta2.RepresentationType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta2.RepresentationType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.project_kessel.api.inventory.v1beta2.RepresentationType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.project_kessel.api.inventory.v1beta2.RepresentationType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta2.RepresentationType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta2.RepresentationType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.project_kessel.api.inventory.v1beta2.RepresentationType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kessel.inventory.v1beta2.RepresentationType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kessel.inventory.v1beta2.RepresentationType)
      org.project_kessel.api.inventory.v1beta2.RepresentationTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta2.RepresentationTypeOuterClass.internal_static_kessel_inventory_v1beta2_RepresentationType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.project_kessel.api.inventory.v1beta2.RepresentationTypeOuterClass.internal_static_kessel_inventory_v1beta2_RepresentationType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project_kessel.api.inventory.v1beta2.RepresentationType.class, org.project_kessel.api.inventory.v1beta2.RepresentationType.Builder.class);
    }

    // Construct using org.project_kessel.api.inventory.v1beta2.RepresentationType.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      resourceType_ = "";
      reporterType_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.project_kessel.api.inventory.v1beta2.RepresentationTypeOuterClass.internal_static_kessel_inventory_v1beta2_RepresentationType_descriptor;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta2.RepresentationType getDefaultInstanceForType() {
      return org.project_kessel.api.inventory.v1beta2.RepresentationType.getDefaultInstance();
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta2.RepresentationType build() {
      org.project_kessel.api.inventory.v1beta2.RepresentationType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta2.RepresentationType buildPartial() {
      org.project_kessel.api.inventory.v1beta2.RepresentationType result = new org.project_kessel.api.inventory.v1beta2.RepresentationType(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.project_kessel.api.inventory.v1beta2.RepresentationType result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.resourceType_ = resourceType_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.reporterType_ = reporterType_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.project_kessel.api.inventory.v1beta2.RepresentationType) {
        return mergeFrom((org.project_kessel.api.inventory.v1beta2.RepresentationType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.project_kessel.api.inventory.v1beta2.RepresentationType other) {
      if (other == org.project_kessel.api.inventory.v1beta2.RepresentationType.getDefaultInstance()) return this;
      if (!other.getResourceType().isEmpty()) {
        resourceType_ = other.resourceType_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasReporterType()) {
        reporterType_ = other.reporterType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              resourceType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              reporterType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object resourceType_ = "";
    /**
     * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
     * @return The resourceType.
     */
    public java.lang.String getResourceType() {
      java.lang.Object ref = resourceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
     * @return The bytes for resourceType.
     */
    public com.google.protobuf.ByteString
        getResourceTypeBytes() {
      java.lang.Object ref = resourceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
     * @param value The resourceType to set.
     * @return This builder for chaining.
     */
    public Builder setResourceType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resourceType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearResourceType() {
      resourceType_ = getDefaultInstance().getResourceType();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for resourceType to set.
     * @return This builder for chaining.
     */
    public Builder setResourceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resourceType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object reporterType_ = "";
    /**
     * <code>optional string reporter_type = 2 [json_name = "reporterType", (.buf.validate.field) = { ... }</code>
     * @return Whether the reporterType field is set.
     */
    public boolean hasReporterType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string reporter_type = 2 [json_name = "reporterType", (.buf.validate.field) = { ... }</code>
     * @return The reporterType.
     */
    public java.lang.String getReporterType() {
      java.lang.Object ref = reporterType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reporterType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string reporter_type = 2 [json_name = "reporterType", (.buf.validate.field) = { ... }</code>
     * @return The bytes for reporterType.
     */
    public com.google.protobuf.ByteString
        getReporterTypeBytes() {
      java.lang.Object ref = reporterType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reporterType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string reporter_type = 2 [json_name = "reporterType", (.buf.validate.field) = { ... }</code>
     * @param value The reporterType to set.
     * @return This builder for chaining.
     */
    public Builder setReporterType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      reporterType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string reporter_type = 2 [json_name = "reporterType", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearReporterType() {
      reporterType_ = getDefaultInstance().getReporterType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string reporter_type = 2 [json_name = "reporterType", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for reporterType to set.
     * @return This builder for chaining.
     */
    public Builder setReporterTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      reporterType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:kessel.inventory.v1beta2.RepresentationType)
  }

  // @@protoc_insertion_point(class_scope:kessel.inventory.v1beta2.RepresentationType)
  private static final org.project_kessel.api.inventory.v1beta2.RepresentationType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.project_kessel.api.inventory.v1beta2.RepresentationType();
  }

  public static org.project_kessel.api.inventory.v1beta2.RepresentationType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RepresentationType>
      PARSER = new com.google.protobuf.AbstractParser<RepresentationType>() {
    @java.lang.Override
    public RepresentationType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RepresentationType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RepresentationType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta2.RepresentationType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

