// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/resource_reference.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

/**
 * Protobuf type {@code kessel.inventory.v1beta2.ResourceReference}
 */
@com.google.protobuf.Generated
public final class ResourceReference extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:kessel.inventory.v1beta2.ResourceReference)
    ResourceReferenceOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      ResourceReference.class.getName());
  }
  // Use ResourceReference.newBuilder() to construct.
  private ResourceReference(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResourceReference() {
    resourceType_ = "";
    resourceId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.project_kessel.api.inventory.v1beta2.ResourceReferenceOuterClass.internal_static_kessel_inventory_v1beta2_ResourceReference_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.project_kessel.api.inventory.v1beta2.ResourceReferenceOuterClass.internal_static_kessel_inventory_v1beta2_ResourceReference_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.project_kessel.api.inventory.v1beta2.ResourceReference.class, org.project_kessel.api.inventory.v1beta2.ResourceReference.Builder.class);
  }

  private int bitField0_;
  public static final int RESOURCE_TYPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resourceType_ = "";
  /**
   * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
   * @return The resourceType.
   */
  @java.lang.Override
  public java.lang.String getResourceType() {
    java.lang.Object ref = resourceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceType_ = s;
      return s;
    }
  }
  /**
   * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
   * @return The bytes for resourceType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceTypeBytes() {
    java.lang.Object ref = resourceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESOURCE_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object resourceId_ = "";
  /**
   * <code>string resource_id = 2 [json_name = "resourceId", (.buf.validate.field) = { ... }</code>
   * @return The resourceId.
   */
  @java.lang.Override
  public java.lang.String getResourceId() {
    java.lang.Object ref = resourceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resourceId_ = s;
      return s;
    }
  }
  /**
   * <code>string resource_id = 2 [json_name = "resourceId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for resourceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResourceIdBytes() {
    java.lang.Object ref = resourceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resourceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPORTER_FIELD_NUMBER = 3;
  private org.project_kessel.api.inventory.v1beta2.ReporterReference reporter_;
  /**
   * <code>optional .kessel.inventory.v1beta2.ReporterReference reporter = 3 [json_name = "reporter"];</code>
   * @return Whether the reporter field is set.
   */
  @java.lang.Override
  public boolean hasReporter() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .kessel.inventory.v1beta2.ReporterReference reporter = 3 [json_name = "reporter"];</code>
   * @return The reporter.
   */
  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta2.ReporterReference getReporter() {
    return reporter_ == null ? org.project_kessel.api.inventory.v1beta2.ReporterReference.getDefaultInstance() : reporter_;
  }
  /**
   * <code>optional .kessel.inventory.v1beta2.ReporterReference reporter = 3 [json_name = "reporter"];</code>
   */
  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta2.ReporterReferenceOrBuilder getReporterOrBuilder() {
    return reporter_ == null ? org.project_kessel.api.inventory.v1beta2.ReporterReference.getDefaultInstance() : reporter_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourceType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, resourceType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourceId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, resourceId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getReporter());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourceType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, resourceType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(resourceId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, resourceId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getReporter());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.project_kessel.api.inventory.v1beta2.ResourceReference)) {
      return super.equals(obj);
    }
    org.project_kessel.api.inventory.v1beta2.ResourceReference other = (org.project_kessel.api.inventory.v1beta2.ResourceReference) obj;

    if (!getResourceType()
        .equals(other.getResourceType())) return false;
    if (!getResourceId()
        .equals(other.getResourceId())) return false;
    if (hasReporter() != other.hasReporter()) return false;
    if (hasReporter()) {
      if (!getReporter()
          .equals(other.getReporter())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESOURCE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getResourceType().hashCode();
    hash = (37 * hash) + RESOURCE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getResourceId().hashCode();
    if (hasReporter()) {
      hash = (37 * hash) + REPORTER_FIELD_NUMBER;
      hash = (53 * hash) + getReporter().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.project_kessel.api.inventory.v1beta2.ResourceReference parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta2.ResourceReference parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta2.ResourceReference parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta2.ResourceReference parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta2.ResourceReference parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.project_kessel.api.inventory.v1beta2.ResourceReference parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta2.ResourceReference parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta2.ResourceReference parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.project_kessel.api.inventory.v1beta2.ResourceReference parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.project_kessel.api.inventory.v1beta2.ResourceReference parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.project_kessel.api.inventory.v1beta2.ResourceReference parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.project_kessel.api.inventory.v1beta2.ResourceReference parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.project_kessel.api.inventory.v1beta2.ResourceReference prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kessel.inventory.v1beta2.ResourceReference}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kessel.inventory.v1beta2.ResourceReference)
      org.project_kessel.api.inventory.v1beta2.ResourceReferenceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.project_kessel.api.inventory.v1beta2.ResourceReferenceOuterClass.internal_static_kessel_inventory_v1beta2_ResourceReference_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.project_kessel.api.inventory.v1beta2.ResourceReferenceOuterClass.internal_static_kessel_inventory_v1beta2_ResourceReference_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.project_kessel.api.inventory.v1beta2.ResourceReference.class, org.project_kessel.api.inventory.v1beta2.ResourceReference.Builder.class);
    }

    // Construct using org.project_kessel.api.inventory.v1beta2.ResourceReference.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetReporterFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      resourceType_ = "";
      resourceId_ = "";
      reporter_ = null;
      if (reporterBuilder_ != null) {
        reporterBuilder_.dispose();
        reporterBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.project_kessel.api.inventory.v1beta2.ResourceReferenceOuterClass.internal_static_kessel_inventory_v1beta2_ResourceReference_descriptor;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta2.ResourceReference getDefaultInstanceForType() {
      return org.project_kessel.api.inventory.v1beta2.ResourceReference.getDefaultInstance();
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta2.ResourceReference build() {
      org.project_kessel.api.inventory.v1beta2.ResourceReference result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.project_kessel.api.inventory.v1beta2.ResourceReference buildPartial() {
      org.project_kessel.api.inventory.v1beta2.ResourceReference result = new org.project_kessel.api.inventory.v1beta2.ResourceReference(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.project_kessel.api.inventory.v1beta2.ResourceReference result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.resourceType_ = resourceType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.resourceId_ = resourceId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.reporter_ = reporterBuilder_ == null
            ? reporter_
            : reporterBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.project_kessel.api.inventory.v1beta2.ResourceReference) {
        return mergeFrom((org.project_kessel.api.inventory.v1beta2.ResourceReference)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.project_kessel.api.inventory.v1beta2.ResourceReference other) {
      if (other == org.project_kessel.api.inventory.v1beta2.ResourceReference.getDefaultInstance()) return this;
      if (!other.getResourceType().isEmpty()) {
        resourceType_ = other.resourceType_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getResourceId().isEmpty()) {
        resourceId_ = other.resourceId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasReporter()) {
        mergeReporter(other.getReporter());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              resourceType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              resourceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetReporterFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object resourceType_ = "";
    /**
     * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
     * @return The resourceType.
     */
    public java.lang.String getResourceType() {
      java.lang.Object ref = resourceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
     * @return The bytes for resourceType.
     */
    public com.google.protobuf.ByteString
        getResourceTypeBytes() {
      java.lang.Object ref = resourceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
     * @param value The resourceType to set.
     * @return This builder for chaining.
     */
    public Builder setResourceType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resourceType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearResourceType() {
      resourceType_ = getDefaultInstance().getResourceType();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string resource_type = 1 [json_name = "resourceType", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for resourceType to set.
     * @return This builder for chaining.
     */
    public Builder setResourceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resourceType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object resourceId_ = "";
    /**
     * <code>string resource_id = 2 [json_name = "resourceId", (.buf.validate.field) = { ... }</code>
     * @return The resourceId.
     */
    public java.lang.String getResourceId() {
      java.lang.Object ref = resourceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resourceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string resource_id = 2 [json_name = "resourceId", (.buf.validate.field) = { ... }</code>
     * @return The bytes for resourceId.
     */
    public com.google.protobuf.ByteString
        getResourceIdBytes() {
      java.lang.Object ref = resourceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resourceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string resource_id = 2 [json_name = "resourceId", (.buf.validate.field) = { ... }</code>
     * @param value The resourceId to set.
     * @return This builder for chaining.
     */
    public Builder setResourceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      resourceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string resource_id = 2 [json_name = "resourceId", (.buf.validate.field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearResourceId() {
      resourceId_ = getDefaultInstance().getResourceId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string resource_id = 2 [json_name = "resourceId", (.buf.validate.field) = { ... }</code>
     * @param value The bytes for resourceId to set.
     * @return This builder for chaining.
     */
    public Builder setResourceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      resourceId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private org.project_kessel.api.inventory.v1beta2.ReporterReference reporter_;
    private com.google.protobuf.SingleFieldBuilder<
        org.project_kessel.api.inventory.v1beta2.ReporterReference, org.project_kessel.api.inventory.v1beta2.ReporterReference.Builder, org.project_kessel.api.inventory.v1beta2.ReporterReferenceOrBuilder> reporterBuilder_;
    /**
     * <code>optional .kessel.inventory.v1beta2.ReporterReference reporter = 3 [json_name = "reporter"];</code>
     * @return Whether the reporter field is set.
     */
    public boolean hasReporter() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .kessel.inventory.v1beta2.ReporterReference reporter = 3 [json_name = "reporter"];</code>
     * @return The reporter.
     */
    public org.project_kessel.api.inventory.v1beta2.ReporterReference getReporter() {
      if (reporterBuilder_ == null) {
        return reporter_ == null ? org.project_kessel.api.inventory.v1beta2.ReporterReference.getDefaultInstance() : reporter_;
      } else {
        return reporterBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .kessel.inventory.v1beta2.ReporterReference reporter = 3 [json_name = "reporter"];</code>
     */
    public Builder setReporter(org.project_kessel.api.inventory.v1beta2.ReporterReference value) {
      if (reporterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reporter_ = value;
      } else {
        reporterBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .kessel.inventory.v1beta2.ReporterReference reporter = 3 [json_name = "reporter"];</code>
     */
    public Builder setReporter(
        org.project_kessel.api.inventory.v1beta2.ReporterReference.Builder builderForValue) {
      if (reporterBuilder_ == null) {
        reporter_ = builderForValue.build();
      } else {
        reporterBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .kessel.inventory.v1beta2.ReporterReference reporter = 3 [json_name = "reporter"];</code>
     */
    public Builder mergeReporter(org.project_kessel.api.inventory.v1beta2.ReporterReference value) {
      if (reporterBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          reporter_ != null &&
          reporter_ != org.project_kessel.api.inventory.v1beta2.ReporterReference.getDefaultInstance()) {
          getReporterBuilder().mergeFrom(value);
        } else {
          reporter_ = value;
        }
      } else {
        reporterBuilder_.mergeFrom(value);
      }
      if (reporter_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .kessel.inventory.v1beta2.ReporterReference reporter = 3 [json_name = "reporter"];</code>
     */
    public Builder clearReporter() {
      bitField0_ = (bitField0_ & ~0x00000004);
      reporter_ = null;
      if (reporterBuilder_ != null) {
        reporterBuilder_.dispose();
        reporterBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .kessel.inventory.v1beta2.ReporterReference reporter = 3 [json_name = "reporter"];</code>
     */
    public org.project_kessel.api.inventory.v1beta2.ReporterReference.Builder getReporterBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetReporterFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .kessel.inventory.v1beta2.ReporterReference reporter = 3 [json_name = "reporter"];</code>
     */
    public org.project_kessel.api.inventory.v1beta2.ReporterReferenceOrBuilder getReporterOrBuilder() {
      if (reporterBuilder_ != null) {
        return reporterBuilder_.getMessageOrBuilder();
      } else {
        return reporter_ == null ?
            org.project_kessel.api.inventory.v1beta2.ReporterReference.getDefaultInstance() : reporter_;
      }
    }
    /**
     * <code>optional .kessel.inventory.v1beta2.ReporterReference reporter = 3 [json_name = "reporter"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.project_kessel.api.inventory.v1beta2.ReporterReference, org.project_kessel.api.inventory.v1beta2.ReporterReference.Builder, org.project_kessel.api.inventory.v1beta2.ReporterReferenceOrBuilder> 
        internalGetReporterFieldBuilder() {
      if (reporterBuilder_ == null) {
        reporterBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.project_kessel.api.inventory.v1beta2.ReporterReference, org.project_kessel.api.inventory.v1beta2.ReporterReference.Builder, org.project_kessel.api.inventory.v1beta2.ReporterReferenceOrBuilder>(
                getReporter(),
                getParentForChildren(),
                isClean());
        reporter_ = null;
      }
      return reporterBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:kessel.inventory.v1beta2.ResourceReference)
  }

  // @@protoc_insertion_point(class_scope:kessel.inventory.v1beta2.ResourceReference)
  private static final org.project_kessel.api.inventory.v1beta2.ResourceReference DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.project_kessel.api.inventory.v1beta2.ResourceReference();
  }

  public static org.project_kessel.api.inventory.v1beta2.ResourceReference getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceReference>
      PARSER = new com.google.protobuf.AbstractParser<ResourceReference>() {
    @java.lang.Override
    public ResourceReference parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResourceReference> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResourceReference> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.project_kessel.api.inventory.v1beta2.ResourceReference getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

