// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/resource_representations.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

@com.google.protobuf.Generated
public final class ResourceRepresentationsOuterClass {
  private ResourceRepresentationsOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 0,
      /* suffix= */ "",
      ResourceRepresentationsOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kessel_inventory_v1beta2_ResourceRepresentations_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kessel_inventory_v1beta2_ResourceRepresentations_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7kessel/inventory/v1beta2/resource_repr" +
      "esentations.proto\022\030kessel.inventory.v1be" +
      "ta2\032\034google/protobuf/struct.proto\0326kesse" +
      "l/inventory/v1beta2/representation_metad" +
      "ata.proto\032\033buf/validate/validate.proto\"\367" +
      "\001\n\027ResourceRepresentations\022T\n\010metadata\030\001" +
      " \001(\01320.kessel.inventory.v1beta2.Represen" +
      "tationMetadataB\006\272H\003\310\001\001R\010metadata\0224\n\006comm" +
      "on\030\002 \001(\0132\027.google.protobuf.StructH\000R\006com" +
      "mon\210\001\001\0228\n\010reporter\030\003 \001(\0132\027.google.protob" +
      "uf.StructH\001R\010reporter\210\001\001B\t\n\007_commonB\013\n\t_" +
      "reporterBr\n(org.project_kessel.api.inven" +
      "tory.v1beta2P\001ZDgithub.com/project-kesse" +
      "l/inventory-api/api/kessel/inventory/v1b" +
      "eta2b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          org.project_kessel.api.inventory.v1beta2.RepresentationMetadataOuterClass.getDescriptor(),
          build.buf.validate.ValidateProto.getDescriptor(),
        });
    internal_static_kessel_inventory_v1beta2_ResourceRepresentations_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kessel_inventory_v1beta2_ResourceRepresentations_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_kessel_inventory_v1beta2_ResourceRepresentations_descriptor,
        new java.lang.String[] { "Metadata", "Common", "Reporter", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.StructProto.getDescriptor();
    org.project_kessel.api.inventory.v1beta2.RepresentationMetadataOuterClass.getDescriptor();
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
