// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/streamed_list_subjects_request.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

@com.google.protobuf.Generated
public interface StreamedListSubjectsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta2.StreamedListSubjectsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kessel.inventory.v1beta2.ResourceReference resource = 1 [json_name = "resource", (.buf.validate.field) = { ... }</code>
   * @return Whether the resource field is set.
   */
  boolean hasResource();
  /**
   * <code>.kessel.inventory.v1beta2.ResourceReference resource = 1 [json_name = "resource", (.buf.validate.field) = { ... }</code>
   * @return The resource.
   */
  org.project_kessel.api.inventory.v1beta2.ResourceReference getResource();
  /**
   * <code>.kessel.inventory.v1beta2.ResourceReference resource = 1 [json_name = "resource", (.buf.validate.field) = { ... }</code>
   */
  org.project_kessel.api.inventory.v1beta2.ResourceReferenceOrBuilder getResourceOrBuilder();

  /**
   * <code>string relation = 2 [json_name = "relation", (.buf.validate.field) = { ... }</code>
   * @return The relation.
   */
  java.lang.String getRelation();
  /**
   * <code>string relation = 2 [json_name = "relation", (.buf.validate.field) = { ... }</code>
   * @return The bytes for relation.
   */
  com.google.protobuf.ByteString
      getRelationBytes();

  /**
   * <code>.kessel.inventory.v1beta2.RepresentationType subject_type = 3 [json_name = "subjectType", (.buf.validate.field) = { ... }</code>
   * @return Whether the subjectType field is set.
   */
  boolean hasSubjectType();
  /**
   * <code>.kessel.inventory.v1beta2.RepresentationType subject_type = 3 [json_name = "subjectType", (.buf.validate.field) = { ... }</code>
   * @return The subjectType.
   */
  org.project_kessel.api.inventory.v1beta2.RepresentationType getSubjectType();
  /**
   * <code>.kessel.inventory.v1beta2.RepresentationType subject_type = 3 [json_name = "subjectType", (.buf.validate.field) = { ... }</code>
   */
  org.project_kessel.api.inventory.v1beta2.RepresentationTypeOrBuilder getSubjectTypeOrBuilder();

  /**
   * <code>optional string subject_relation = 4 [json_name = "subjectRelation"];</code>
   * @return Whether the subjectRelation field is set.
   */
  boolean hasSubjectRelation();
  /**
   * <code>optional string subject_relation = 4 [json_name = "subjectRelation"];</code>
   * @return The subjectRelation.
   */
  java.lang.String getSubjectRelation();
  /**
   * <code>optional string subject_relation = 4 [json_name = "subjectRelation"];</code>
   * @return The bytes for subjectRelation.
   */
  com.google.protobuf.ByteString
      getSubjectRelationBytes();

  /**
   * <code>optional .kessel.inventory.v1beta2.RequestPagination pagination = 5 [json_name = "pagination"];</code>
   * @return Whether the pagination field is set.
   */
  boolean hasPagination();
  /**
   * <code>optional .kessel.inventory.v1beta2.RequestPagination pagination = 5 [json_name = "pagination"];</code>
   * @return The pagination.
   */
  org.project_kessel.api.inventory.v1beta2.RequestPagination getPagination();
  /**
   * <code>optional .kessel.inventory.v1beta2.RequestPagination pagination = 5 [json_name = "pagination"];</code>
   */
  org.project_kessel.api.inventory.v1beta2.RequestPaginationOrBuilder getPaginationOrBuilder();

  /**
   * <code>optional .kessel.inventory.v1beta2.Consistency consistency = 6 [json_name = "consistency"];</code>
   * @return Whether the consistency field is set.
   */
  boolean hasConsistency();
  /**
   * <code>optional .kessel.inventory.v1beta2.Consistency consistency = 6 [json_name = "consistency"];</code>
   * @return The consistency.
   */
  org.project_kessel.api.inventory.v1beta2.Consistency getConsistency();
  /**
   * <code>optional .kessel.inventory.v1beta2.Consistency consistency = 6 [json_name = "consistency"];</code>
   */
  org.project_kessel.api.inventory.v1beta2.ConsistencyOrBuilder getConsistencyOrBuilder();
}
