// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: kessel/inventory/v1beta2/subject_reference.proto
// Protobuf Java Version: 4.32.0

package org.project_kessel.api.inventory.v1beta2;

@com.google.protobuf.Generated
public interface SubjectReferenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kessel.inventory.v1beta2.SubjectReference)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * An optional relation which points to a set of Subjects instead of the single Subject.
   * e.g. "members" or "owners" of a group identified in `subject`.
   * </pre>
   *
   * <code>optional string relation = 1 [json_name = "relation"];</code>
   * @return Whether the relation field is set.
   */
  boolean hasRelation();
  /**
   * <pre>
   * An optional relation which points to a set of Subjects instead of the single Subject.
   * e.g. "members" or "owners" of a group identified in `subject`.
   * </pre>
   *
   * <code>optional string relation = 1 [json_name = "relation"];</code>
   * @return The relation.
   */
  java.lang.String getRelation();
  /**
   * <pre>
   * An optional relation which points to a set of Subjects instead of the single Subject.
   * e.g. "members" or "owners" of a group identified in `subject`.
   * </pre>
   *
   * <code>optional string relation = 1 [json_name = "relation"];</code>
   * @return The bytes for relation.
   */
  com.google.protobuf.ByteString
      getRelationBytes();

  /**
   * <code>.kessel.inventory.v1beta2.ResourceReference resource = 2 [json_name = "resource", (.buf.validate.field) = { ... }</code>
   * @return Whether the resource field is set.
   */
  boolean hasResource();
  /**
   * <code>.kessel.inventory.v1beta2.ResourceReference resource = 2 [json_name = "resource", (.buf.validate.field) = { ... }</code>
   * @return The resource.
   */
  org.project_kessel.api.inventory.v1beta2.ResourceReference getResource();
  /**
   * <code>.kessel.inventory.v1beta2.ResourceReference resource = 2 [json_name = "resource", (.buf.validate.field) = { ... }</code>
   */
  org.project_kessel.api.inventory.v1beta2.ResourceReferenceOrBuilder getResourceOrBuilder();
}
